-- Migration 038: Refresh Tushare catalog from current official CSV
-- Date: 2026-04-20
-- Generated from quantmate-docs/reference/tushare_api_full.csv

CREATE TEMPORARY TABLE IF NOT EXISTS `_tmp_tushare_catalog_refresh` (
    `source` VARCHAR(50) NOT NULL,
    `item_key` VARCHAR(100) NOT NULL,
    `item_name` VARCHAR(200) NOT NULL,
    `enabled` TINYINT(1) NOT NULL DEFAULT 0,
    `description` TEXT DEFAULT NULL,
    `category` VARCHAR(50) DEFAULT NULL,
    `sub_category` VARCHAR(50) DEFAULT NULL,
    `api_name` VARCHAR(100) DEFAULT NULL,
    `permission_points` INT NOT NULL DEFAULT 0,
    `rate_limit_note` VARCHAR(200) DEFAULT NULL,
    `requires_permission` VARCHAR(50) DEFAULT NULL,
    `target_database` VARCHAR(50) NOT NULL DEFAULT "tushare",
    `target_table` VARCHAR(100) NOT NULL,
    `table_created` TINYINT(1) NOT NULL DEFAULT 0,
    `sync_priority` INT NOT NULL DEFAULT 100,
    PRIMARY KEY (`source`, `item_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `_tmp_tushare_catalog_refresh`;

INSERT INTO `_tmp_tushare_catalog_refresh`
  (`source`, `item_key`, `item_name`, `enabled`, `description`, `category`, `sub_category`, `api_name`, `permission_points`, `rate_limit_note`, `requires_permission`, `target_database`, `target_table`, `table_created`, `sync_priority`)
VALUES
    ('tushare', 'trade_cal', '交易日历', 1, '获取各大交易所交易日历数据,默认提取的是上交所', '股票数据', '基础数据', 'trade_cal', 2000, '', '0', 'tushare', 'trade_cal', 0, 5),
    ('tushare', 'stock_basic', '股票基础列表', 1, '获取基础信息数据，包括股票代码、名称、上市日期、退市日期等', '股票数据', '基础数据', 'stock_basic', 2000, '每次最多返回6000行数据（覆盖全市场A股，会随股票总数增长而增加）', '0', 'tushare', 'stock_basic', 0, 10),
    ('tushare', 'stock_company', '上市公司信息', 1, '获取上市公司基础信息，单次提取4500条，可以根据交易所分批提取', '股票数据', '基础数据', 'stock_company', 120, '', '0', 'tushare', 'stock_company', 1, 15),
    ('tushare', 'stock_daily', 'A股日线行情', 1, '获取股票行情数据，或通过', '股票数据', '行情数据', 'daily', 120, '', '0', 'tushare', 'stock_daily', 1, 20),
    ('tushare', 'bak_daily', '备用行情', 1, '获取备用行情，包括特定的行情指标(数据从2017年中左右开始，早期有几天数据缺失，近期正常)', '股票数据', '行情数据', 'bak_daily', 5000, '单次最大7000行数据，可以根据日期参数循环获取，正式权限需要5000积分', '0', 'tushare', 'bak_daily', 0, 22),
    ('tushare', 'suspend_d', '每日停复牌信息', 1, '按日期方式获取股票每日停复牌信息', '股票数据', '行情数据', 'suspend_d', 120, '', '0', 'tushare', 'suspend_d', 1, 23),
    ('tushare', 'suspend', '停复牌历史', 1, '停复牌历史数据', '股票数据', '行情数据', 'suspend', 120, '单次最大6000行', '0', 'tushare', 'suspend', 0, 24),
    ('tushare', 'moneyflow', '个股资金流向', 1, '获取沪深A股票资金流向数据，分析大单小单成交情况，用于判别资金动向，数据开始于2010年', '股票数据', '行情数据', 'moneyflow', 2000, '单次最大提取6000行记录，总量不限制', '0', 'tushare', 'stock_moneyflow', 0, 25),
    ('tushare', 'stock_weekly', '周线行情', 1, '获取A股周线行情，本接口每周最后一个交易日更新，如需要使用每天更新的周线数据，请使用', '股票数据', '行情数据', 'weekly', 2000, '单次最大6000行，可使用交易日期循环提取，总量不限制', '0', 'tushare', 'stock_weekly', 0, 25),
    ('tushare', 'stock_monthly', '月线行情', 1, '获取A股月线数据', '股票数据', '行情数据', 'monthly', 2000, '单次最大4500行，总量不限制', '0', 'tushare', 'stock_monthly', 0, 26),
    ('tushare', 'index_daily', '指数日线行情', 1, '获取指数每日行情，还可以通过bar接口获取。由于服务器压力，目前规则是单次调取最多取8000行记录，可以设置start和end日期补全。指数行情也可以通过', '指数数据', '行情数据', 'index_daily', 2000, '', '0', 'tushare', 'index_daily', 0, 27),
    ('tushare', 'index_weekly', '指数周线行情', 1, '获取指数周线行情', '指数数据', '行情数据', 'index_weekly', 600, '单次最大1000行记录，可分批获取，总量不限制', '0', 'tushare', 'index_weekly', 0, 28),
    ('tushare', 'adj_factor', '复权因子', 0, '本接口由Tushare自行生产，获取股票复权因子，可提取单只股票全部历史复权因子，也可以提取单日全部股票的复权因子', '股票数据', '行情数据', 'adj_factor', 120, '', '0', 'tushare', 'adj_factor', 0, 30),
    ('tushare', 'daily_basic', '每日指标数据', 0, '获取全部股票每日重要的基本面指标，可用于选股分析、报表展示等。单次请求最大返回6000条数据，可按日线循环提取全部历史', '股票数据', '行情数据', 'daily_basic', 2000, '', '0', 'tushare', 'daily_basic', 0, 31),
    ('tushare', 'dividend', '分红送股', 0, '分红送股数据', '股票数据', '财务数据', 'dividend', 2000, '', '0', 'tushare', 'stock_dividend', 0, 50),
    ('tushare', 'fina_indicator', '财务指标数据', 0, '获取上市公司财务指标数据，为避免服务器压力，现阶段每次请求最多返回100条记录，可通过设置日期多次请求获取更多数据', '股票数据', '财务数据', 'fina_indicator', 2000, '', '0', 'tushare', 'fina_indicator', 0, 55),
    ('tushare', 'income', '利润表', 0, '获取上市公司财务利润表数据', '股票数据', '财务数据', 'income', 2000, '', '0', 'tushare', 'income', 0, 56),
    ('tushare', 'top10_holders', '前十大股东', 0, '获取上市公司前十大股东数据，包括持有数量和比例等信息', '股票数据', '参考数据', 'top10_holders', 2000, '', '0', 'tushare', 'top10_holders', 0, 57),
    ('tushare', 'limit_list_d', '涨跌停统计', 0, '获取A股每日涨跌停、炸板数据情况，数据从2020年开始（不提供ST股票的统计）', '股票数据', '行情数据', 'limit_list_d', 5000, '单次最大可以获取2500条数据，可通过日期或者股票循环提取', '0', 'tushare', 'limit_list_d', 0, 70),
    ('tushare', 'stk_limit', '每日涨跌停价格', 1, '获取全市场（包含A/B股和基金）每日涨跌停价格，包括涨停价格，跌停价格等，每个交易日8点40左右更新当日股票涨跌停价格', '股票数据', '行情数据', 'stk_limit', 2000, '单次最多提取5800条记录，可循环调取，总量不限制', '0', 'tushare', 'stk_limit', 0, 70),
    ('tushare', 'margin_detail', '融资融券明细', 0, '获取沪深两市每日融资融券明细', '股票数据', '行情数据', 'margin_detail', 2000, '单次请求最大返回6000行数据，可根据日期循环', '0', 'tushare', 'margin', 0, 80),
    ('tushare', 'margin', '融资融券', 0, '获取融资融券每日交易汇总数据', '股票数据', '行情数据', 'margin', 2000, '单次请求最大返回4000行数据，可根据日期循环', '0', 'tushare', 'margin_summary', 0, 81),
    ('tushare', 'block_trade', '大宗交易', 1, '大宗交易', '股票数据', '特色数据', 'block_trade', 300, '单次最大1000条，总量不限制', '0', 'tushare', 'block_trade', 0, 90),
    ('tushare', 'hsgt_top10', '沪深股通成份股', 0, '获取沪股通、深股通每日前十大成交详细数据，每天18~20点之间完成当日更新', '股票数据', '基础数据', 'hsgt_top10', 2000, '', '0', 'tushare', 'hsgt_top10', 0, 100),
    ('tushare', 'namechange', '股票曾用名', 0, '历史名称变更记录', '股票数据', '基础数据', 'namechange', 2000, '', '0', 'tushare', 'namechange', 0, 103),
    ('tushare', 'new_share', 'IPO新股列表', 0, '获取新股上市列表数据', '股票数据', '基础数据', 'new_share', 120, '单次最大2000条，总量不限制', '0', 'tushare', 'new_share', 1, 104),
    ('tushare', 'stk_holdertrade', '董监高持股', 0, '获取上市公司增减持数据，了解重要股东近期及历史上的股份增减变化', '股票数据', '基础数据', 'stk_holdertrade', 2000, '单次最大提取3000行记录，总量不限制', '0', 'tushare', 'stk_holdertrade', 0, 109),
    ('tushare', 'balancesheet', '资产负债表', 0, '获取上市公司资产负债表', '股票数据', '财务数据', 'balancesheet', 2000, '', '0', 'tushare', 'balancesheet', 0, 201),
    ('tushare', 'cashflow', '现金流量表', 0, '获取上市公司现金流量表', '股票数据', '财务数据', 'cashflow', 2000, '', '0', 'tushare', 'cashflow', 0, 203),
    ('tushare', 'forecast', '业绩预告', 0, '获取业绩预告数据', '股票数据', '财务数据', 'forecast', 2000, '', '0', 'tushare', 'forecast', 0, 205),
    ('tushare', 'express', '业绩快报', 0, '获取上市公司业绩快报', '股票数据', '财务数据', 'express', 2000, '', '0', 'tushare', 'express', 0, 206),
    ('tushare', 'fina_audit', '财务审计意见', 0, '获取上市公司定期财务审计意见数据', '股票数据', '财务数据', 'fina_audit', 2000, '', '0', 'tushare', 'fina_audit', 0, 208),
    ('tushare', 'fina_mainbz', '主营业务构成', 0, '获得上市公司主营业务构成，分地区和产品两种方式', '股票数据', '财务数据', 'fina_mainbz', 2000, '', '0', 'tushare', 'fina_mainbz', 0, 209),
    ('tushare', 'disclosure_date', '财报披露计划', 0, '获取财报披露计划日期', '股票数据', '财务数据', 'disclosure_date', 500, '单次最大3000，总量不限制', '0', 'tushare', 'disclosure_date', 0, 211),
    ('tushare', 'top_list', '龙虎榜每日明细', 0, '龙虎榜每日交易明细', '股票数据', '特色数据', 'top_list', 2000, '单次请求返回最大10000行数据，可通过参数循环获取全部历史', '0', 'tushare', 'top_list', 0, 300),
    ('tushare', 'top_inst', '龙虎榜机构交易明细', 0, '龙虎榜机构成交明细', '股票数据', '特色数据', 'top_inst', 5000, '单次请求最大返回10000行数据，可根据参数循环获取全部历史', '0', 'tushare', 'top_inst', 0, 301),
    ('tushare', 'pledge_detail', '股权质押明细', 0, '获取股票质押明细数据', '股票数据', '特色数据', 'pledge_detail', 500, '单次最大1000', '0', 'tushare', 'pledge_detail', 0, 302),
    ('tushare', 'pledge_stat', '股权质押统计', 0, '获取股票质押统计数据', '股票数据', '特色数据', 'pledge_stat', 2000, '单次最大1000', '0', 'tushare', 'pledge_stat', 0, 303),
    ('tushare', 'repurchase', '股票回购', 0, '获取上市公司回购股票数据', '股票数据', '特色数据', 'repurchase', 600, '', '0', 'tushare', 'repurchase', 0, 304),
    ('tushare', 'share_float', '限售股解禁', 0, '获取限售股解禁', '股票数据', '特色数据', 'share_float', 120, '单次最大6000条，总量不限制', '0', 'tushare', 'share_float', 0, 305),
    ('tushare', 'stk_factor_pro', '股票技术面因子', 0, '获取股票每日技术面因子数据，用于跟踪股票当前走势情况，数据由Tushare社区自产，覆盖全历史；输出参数_bfq表示不复权，_qfq表示前复权 _hfq表示后复权，描述中说明了因子的默认传参，如需要特殊参数或者更多因子可以联系管理员评估', '股票数据', '股票因子', 'stk_factor_pro', 5000, '单次调取最多返回10000条数据，可以通过日期参数循环', '0', 'tushare', 'stk_factor_pro', 0, 307),
    ('tushare', 'cyq_perf', '每日筹码及胜率', 0, '获取A股每日筹码平均成本和胜率情况，每天18~19点左右更新，数据从2018年开始', '股票数据', '特色数据', 'cyq_perf', 5000, '单次最大5000条，可以分页或者循环提取', '0', 'tushare', 'cyq_perf', 0, 309),
    ('tushare', 'cyq_chips', '筹码分布', 0, '获取A股每日的筹码分布情况，提供各价位占比，数据从2018年开始，每天18~19点之间更新当日数据', '股票数据', '特色数据', 'cyq_chips', 5000, '单次最大2000条，可以按股票代码和日期循环提取', '0', 'tushare', 'cyq_chips', 0, 310),
    ('tushare', 'kpl_list', '开盘啦榜单', 0, '获取开盘啦涨停、跌停、炸板等榜单数据', '股票数据', '特色数据', 'kpl_list', 5000, '单次最大8000条数据，可根据日期循环获取历史数据', '0', 'tushare', 'kpl_list', 0, 311),
    ('tushare', 'dc_hot', '东方财富热榜', 0, '获取东方财富App热榜数据，包括A股市场、ETF基金、港股市场、美股市场等等，每日盘中提取4次，收盘后4次，最晚22点提取一次', '股票数据', '特色数据', 'dc_hot', 8000, '单次最大2000条，可根据日期等参数循环获取全部数据', '0', 'tushare', 'dc_hot', 0, 312),
    ('tushare', 'dc_member', '东方财富板块成分', 0, '获取东方财富板块每日成分数据，可以根据概念板块代码和交易日期，获取历史成分', '股票数据', '特色数据', 'dc_member', 6000, '单次最大获取5000条数据，可以通过日期和代码循环获取', '0', 'tushare', 'dc_member', 0, 313),
    ('tushare', 'report_rc', '盈利预测数据', 0, '获取券商（卖方）每天研报的盈利预测数据，数据从2010年开始，每晚19~22点更新当日数据', '股票数据', '特色数据', 'report_rc', 120, '单次最大3000条，可分页和循环提取所有数据', '0', 'tushare', 'report_rc', 1, 315),
    ('tushare', 'index_basic', '指数基本信息', 0, '获取指数基础信息', '指数数据', '基础数据', 'index_basic', 2000, '', '0', 'tushare', 'index_basic', 0, 400),
    ('tushare', 'index_monthly', '指数月线行情', 0, '获取指数月线行情,每月更新一次', '指数数据', '行情数据', 'index_monthly', 600, '单次最大1000行记录,可多次获取,总量不限制', '0', 'tushare', 'index_monthly', 0, 401),
    ('tushare', 'index_weight', '指数成分和权重', 0, '获取各类指数成分和权重，', '指数数据', '成分数据', 'index_weight', 2000, '', '0', 'tushare', 'index_weight', 0, 402),
    ('tushare', 'index_dailybasic', '大盘指数每日指标', 0, '目前只提供上证综指，深证成指，上证50，中证500，中小板指，创业板指的每日指标数据', '指数数据', '大盘数据', 'index_dailybasic', 4000, '', '0', 'tushare', 'index_dailybasic', 0, 403),
    ('tushare', 'index_classify', '申万行业分类', 0, '获取申万行业分类，可以获取申万2014年版本（28个一级分类，104个二级分类，227个三级分类）和2021年本版（31个一级分类，134个二级分类，346个三级分类）列表信息', '指数数据', '行业分类', 'index_classify', 2000, '', '0', 'tushare', 'index_classify', 0, 404),
    ('tushare', 'index_member_all', '申万行业成分', 0, '按三级分类提取申万行业成分，可提供某个分类的所有成分，也可按股票代码提取所属分类，参数灵活', '指数数据', '行业分类', 'index_member_all', 2000, '单次最大2000行，总量不限制', '0', 'tushare', 'index_member_all', 0, 405),
    ('tushare', 'index_global', '国际指数', 0, '获取国际主要指数日线行情', '指数数据', '国际指数', 'index_global', 6000, '单次最大提取4000行情数据，可循环获取，总量不限制', '0', 'tushare', 'index_global', 0, 406),
    ('tushare', 'fund_share', 'ETF基金规模', 0, '获取基金规模数据，包含上海和深圳ETF基金', 'ETF专题', 'ETF数据', 'fund_share', 2000, '单次最大提取2000行数据', '0', 'tushare', 'fund_share', 0, 501),
    ('tushare', 'fund_daily', '场内基金日线行情', 0, '获取ETF行情每日收盘后成交数据，历史超过10年', 'ETF专题', 'ETF数据', 'fund_daily', 5000, '单次最大5000行记录，可以根据ETF代码和日期循环获取历史，总量不限制', '0', 'tushare', 'fund_daily', 0, 502),
    ('tushare', 'fund_adj', 'ETF复权因子', 0, '获取基金复权因子，用于计算基金复权行情', 'ETF专题', 'ETF数据', 'fund_adj', 600, '单次最大提取2000行记录，可循环提取，数据总量不限制', '0', 'tushare', 'fund_adj', 0, 503),
    ('tushare', 'fund_basic', '公募基金列表', 0, '获取公募基金数据列表，包括场内和场外基金', '公募基金', '基金基础', 'fund_basic', 2000, '单次最大可以提取15000条数据', '0', 'tushare', 'fund_basic', 0, 510),
    ('tushare', 'fund_company', '公募基金公司', 0, '获取公募基金管理人列表', '公募基金', '基金基础', 'fund_company', 1500, '', '0', 'tushare', 'fund_company', 0, 511),
    ('tushare', 'fund_nav', '公募基金净值', 0, '获取公募基金净值数据', '公募基金', '基金净值', 'fund_nav', 2000, '', '0', 'tushare', 'fund_nav', 0, 512),
    ('tushare', 'fund_div', '公募基金分红', 0, '获取公募基金分红数据', '公募基金', '基金分红', 'fund_div', 400, '', '0', 'tushare', 'fund_div', 0, 514),
    ('tushare', 'fund_portfolio', '公募基金持仓数据', 0, '获取公募基金持仓数据，季度更新', '公募基金', '基金持仓', 'fund_portfolio', 5000, '', '0', 'tushare', 'fund_portfolio', 0, 515),
    ('tushare', 'fut_basic', '期货合约列表', 0, '获取期货合约列表数据', '期货数据', '合约数据', 'fut_basic', 2000, '单次最大10000', '0', 'tushare', 'fut_basic', 0, 600),
    ('tushare', 'fut_daily', '期货日线行情', 0, '期货日线行情数据', '期货数据', '行情数据', 'fut_daily', 2000, '单次最大2000条，总量不限制', '0', 'tushare', 'fut_daily', 0, 602),
    ('tushare', 'fut_holding', '每日成交持仓排名', 0, '获取每日成交持仓排名数据', '期货数据', '持仓数据', 'fut_holding', 2000, '单次最大2000，总量不限制', '0', 'tushare', 'fut_holding', 0, 603),
    ('tushare', 'fut_wsr', '仓单日报', 0, '获取仓单日报数据，了解各仓库/厂库的仓单变化', '期货数据', '仓单数据', 'fut_wsr', 2000, '单次最大1000，总量不限制', '0', 'tushare', 'fut_wsr', 0, 604),
    ('tushare', 'fut_settle', '结算参数', 0, '获取每日结算参数数据，包括交易和交割费率等', '期货数据', '结算数据', 'fut_settle', 2000, '单次最大返回1600行数据，可根据日期循环，总量不限制', '0', 'tushare', 'fut_settle', 0, 605),
    ('tushare', 'fut_mapping', '合约交叉引用', 0, '获取期货主力（或连续）合约与月合约映射数据', '期货数据', '关联合约', 'fut_mapping', 2000, '单次最大2000条，总量不限制', '0', 'tushare', 'fut_mapping', 0, 607),
    ('tushare', 'opt_basic', '期权合约列表', 0, '获取期权合约信息', '期权数据', '合约数据', 'opt_basic', 5000, '', '0', 'tushare', 'opt_basic', 0, 700),
    ('tushare', 'cb_basic', '可转债基础信息', 0, '获取可转债基本信息', '债券专题', '可转债数据', 'cb_basic', 2000, '单次最大2000，总量不限制', '0', 'tushare', 'cb_basic', 0, 750),
    ('tushare', 'cb_issue', '可转债发行数据', 0, '获取可转债发行数据', '债券专题', '可转债数据', 'cb_issue', 2000, '单次最大2000，可多次提取，总量不限制', '0', 'tushare', 'cb_issue', 0, 751),
    ('tushare', 'cb_daily', '可转债日线数据', 0, '获取可转债行情', '债券专题', '可转债数据', 'cb_daily', 2000, '单次最大2000条，可多次提取，总量不限制', '0', 'tushare', 'cb_daily', 0, 752),
    ('tushare', 'cb_share', '可转债待发', 0, '获取可转债转股结果', '债券专题', '可转债数据', 'cb_share', 2000, '单次最大2000，总量不限制', '0', 'tushare', 'cb_share', 0, 753),
    ('tushare', 'fx_obasic', '外汇基础信息', 0, '获取海外外汇基础信息，目前只有FXCM交易商的数据', '外汇数据', '外汇基础', 'fx_obasic', 2000, '', '0', 'tushare', 'fx_obasic', 0, 770),
    ('tushare', 'fx_daily', '外汇日线行情', 0, '获取外汇日线行情', '外汇数据', '外汇行情', 'fx_daily', 2000, '单次最大提取1000行记录，可多次提取，总量不限制', '0', 'tushare', 'fx_daily', 0, 771),
    ('tushare', 'hk_basic', '港股列表', 0, '获取港股列表信息', '港股数据', '港股基础', 'hk_basic', 2000, '', '0', 'tushare', 'hk_basic', 0, 780),
    ('tushare', 'us_basic', '美股列表', 0, '获取美股列表信息', '美股数据', '美股基础', 'us_basic', 120, '单次最大6000，可分页提取', '0', 'tushare', 'us_basic', 1, 800),
    ('tushare', 'us_daily', '美股日线', 0, '获取美股行情（未复权），包括全部股票全历史行情，以及重要的市场和估值指标', '美股数据', '美股行情', 'us_daily', 120, '单次最大6000行数据，可根据日期参数循环提取，开通正式权限后也可支持分页提取全部历史', '0', 'tushare', 'us_daily', 1, 801),
    ('tushare', 'bo_monthly', '电影月度票房', 0, '获取电影月度票房数据', '行业经济', '电影数据', 'bo_monthly', 500, '', '0', 'tushare', 'bo_monthly', 0, 820),
    ('tushare', 'bo_weekly', '电影周票房', 0, '获取周度票房数据', '行业经济', '电影数据', 'bo_weekly', 500, '', '0', 'tushare', 'bo_weekly', 0, 821),
    ('tushare', 'daily_info', '市场交易统计', 0, '获取交易所股票交易统计，包括各板块明细', '行业经济', '市场统计', 'daily_info', 600, '单次最大4000，可循环获取，总量不限制', '0', 'tushare', 'daily_info', 0, 825),
    ('tushare', 'shibor_lpr', 'LPR贷款基础利率', 0, 'LPR贷款基础利率', '宏观经济', '利率数据', 'shibor_lpr', 120, '单次最大4000(相当于单次可提取18年历史)，总量不限制，可通过设置开始和结束日期分段获取', '0', 'tushare', 'shibor_lpr', 1, 840),
    ('tushare', 'shibor', '银行间拆借', 0, 'shibor利率', '宏观经济', '利率数据', 'shibor', 120, '单次最大2000，总量不限制，可通过设置开始和结束日期分段获取', '0', 'tushare', 'shibor', 0, 841),
    ('tushare', 'cn_cpi', '居民消费价格指数（CPI）', 0, '获取CPI居民消费价格数据，包括全国、城市和农村的数据', '宏观经济', '国内宏观', 'cn_cpi', 600, '单次最大5000行，一次可以提取全部数据', '0', 'tushare', 'cn_cpi', 0, 842),
    ('tushare', 'cn_gdp', '国内生产总值（GDP）', 0, '获取国民经济之GDP数据', '宏观经济', '国内宏观', 'cn_gdp', 600, '单次最大10000，一次可以提取全部数据', '0', 'tushare', 'cn_gdp', 0, 843),
    ('tushare', 'stk_mins', '股票实时分钟', 0, '获取A股分钟数据，支持1min/5min/15min/30min/60min行情，提供Python SDK和 http Restful API两种方式', '股票数据', '行情数据', 'stk_mins', 0, '单次最大8000行数据，可以通过股票代码和时间循环获取，本接口可以提供超过10年历史分钟数据', '1', 'tushare', 'stk_mins', 0, 900),
    ('tushare', 'rt_etf_k', 'ETF实时日线', 0, '获取ETF实时日k线行情，支持按ETF代码或代码通配符一次性提取全部ETF实时日k线行情', 'ETF专题', 'ETF数据', 'rt_etf_k', 0, '', '1', 'tushare', 'rt_etf_k', 0, 905),
    ('tushare', 'ft_mins', '期货历史分钟', 0, '获取全市场期货合约分钟数据，支持1min/5min/15min/30min/60min行情，提供Python SDK和 http Restful API两种方式，如果需要主力合约分钟，请先通过主力', '期货数据', '历史分钟', 'ft_mins', 120, '单次最大8000行数据，可以通过期货合约代码和时间循环获取，本接口可以提供超过10年历史分钟数据', '0', 'tushare', 'ft_mins', 0, 906),
    ('tushare', 'opt_mins', '期权历史分钟', 0, '获取全市场期权合约分钟数据，支持1min/5min/15min/30min/60min行情，提供Python SDK和 http Restful API两种方式', '期权数据', '历史分钟', 'opt_mins', 120, '单次最大8000行数据，可以通过合约代码和时间循环获取', '0', 'tushare', 'opt_mins', 0, 909),
    ('tushare', 'hk_daily', '港股日线', 0, '获取港股每日增量和历史行情，每日18点左右更新当日数据', '港股数据', '港股行情', 'hk_daily', 0, '单次最大提取5000行记录，可多次提取，总量不限制', '1', 'tushare', 'hk_daily', 0, 910),
    ('tushare', 'hk_mins', '港股分钟', 0, '港股分钟数据，支持1min/5min/15min/30min/60min行情，提供Python SDK和 http Restful API两种方式', '港股数据', '港股分钟', 'hk_mins', 120, '单次最大8000行数据，可以通过股票代码和日期循环获取', '0', 'tushare', 'hk_mins', 0, 911),
    ('tushare', 'rt_hk_k', '港股实时日线', 0, '获取港股实时日k线行情，支持按股票代码及股票代码通配符一次性提取全部股票实时日k线行情', '港股数据', '实时数据', 'rt_hk_k', 0, '单次最大可提取5000条数据', '1', 'tushare', 'rt_hk_k', 0, 913),
    ('tushare', 'hk_hold', '港股通', 0, '获取沪深港股通持股明细，数据来源港交所', '港股数据', '港股资金', 'hk_hold', 120, '单次最多提取3800条记录，可循环调取，总量不限制', '0', 'tushare', 'hk_hold', 0, 914),
    ('tushare', 'concept_corpus', '概念股语料', 0, '概念股数据用于训练', '大模型语料', '数据标注', 'concept_corpus', 0, '单次最大5000', '1', 'tushare', 'concept_corpus', 0, 919),
    ('tushare', 'stock_corpus', '股吧评论', 0, '股吧评论文本数据', '大模型语料', '数据标注', 'stock_corpus', 0, '单次最大5000', '1', 'tushare', 'stock_corpus', 0, 920),
    ('tushare', 'ann_corpus', '公告摘要', 0, '公告摘要数据', '大模型语料', '数据标注', 'ann_corpus', 0, '单次最大5000', '1', 'tushare', 'ann_corpus', 0, 921),
    ('tushare', 'report_corpus', '研报语料', 0, '券商研报数据', '大模型语料', '数据标注', 'report_corpus', 0, '单次最大5000', '1', 'tushare', 'report_corpus', 0, 922),
    ('tushare', 'news', '新闻快讯', 0, '获取主流新闻网站的快讯新闻数据,提供超过6年以上历史新闻', '资讯数据', '新闻快讯', 'news', 0, '单次最大1500条新闻，可根据时间参数循环提取历史', '1', 'tushare', 'news', 0, 923),
    ('tushare', 'major_news', '新闻通讯', 0, '获取长篇通讯信息，覆盖主要新闻资讯网站，提供超过8年历史新闻', '资讯数据', '新闻通讯', 'major_news', 0, '单次最大400行记录，可循环提取保存到本地', '1', 'tushare', 'major_news', 0, 924),
    ('tushare', 'cctv_news', '新闻联播', 0, '获取新闻联播文字稿数据，数据开始于2017年', '资讯数据', '新闻联播', 'cctv_news', 0, '可根据日期参数循环提取，总量不限制', '1', 'tushare', 'cctv_news', 0, 925),
    ('tushare', 'irm_qa_sh', '上证e互动', 0, '获取上交所e互动董秘问答文本数据。上证e互动是由上海证券交易所建立、上海证券市场所有参与主体无偿使用的沟通平台,旨在引导和促进上市公司、投资者等各市场参与主体之间的信息沟通,构建集中、便捷的互动渠道。本接口数据记录了以上沟通问答的文本数据', '资讯数据', '互动易', 'irm_qa_sh', 120, '单次请求最大返回3000行数据，可根据股票代码，日期等参数循环提取全部数据', '0', 'tushare', 'irm_qa_sh', 0, 928),
    ('tushare', 'irm_qa_sz', '深证互动易', 0, '互动易是由深交所官方推出,供投资者与上市公司直接沟通的平台,一站式公司资讯汇集,提供第一手的互动问答、投资者关系信息、公司声音等内容', '资讯数据', '互动易', 'irm_qa_sz', 120, '单次请求最大返回3000行数据，可根据股票代码，日期等参数循环提取全部数据', '0', 'tushare', 'irm_qa_sz', 0, 929),
    ('tushare', 'stk_premarket', '每日股本（盘前）', 0, '每日开盘前获取当日股票的股本情况，包括总股本和流通股本，涨跌停价格等', '股票数据', '基础数据', 'stk_premarket', 0, '单次最大8000条数据，可循环提取', '0', 'tushare', 'stk_premarket', 0, 1000),
    ('tushare', 'stock_st', 'ST股票列表', 0, '获取ST股票列表，可根据交易日期获取历史上每天的ST列表', '股票数据', '基础数据', 'stock_st', 3000, '', '0', 'tushare', 'stock_st', 0, 1001),
    ('tushare', 'st', 'ST风险警示板股票', 0, 'ST风险警示板股票列表', '股票数据', '基础数据', 'st', 6000, '单次最大1000，可根据股票代码循环获取历史数据', '0', 'tushare', 'st', 0, 1002),
    ('tushare', 'stock_hsgt', '沪深港通股票列表', 0, '获取沪深港通股票列表', '股票数据', '基础数据', 'stock_hsgt', 3000, '', '0', 'tushare', 'stock_hsgt', 0, 1003),
    ('tushare', 'stk_managers', '上市公司管理层', 0, '获取上市公司管理层', '股票数据', '基础数据', 'stk_managers', 2000, '', '0', 'tushare', 'stk_managers', 0, 1004),
    ('tushare', 'stk_rewards', '管理层薪酬和持股', 0, '获取上市公司管理层薪酬和持股', '股票数据', '基础数据', 'stk_rewards', 2000, '', '0', 'tushare', 'stk_rewards', 0, 1005),
    ('tushare', 'bse_mapping', '北交所新旧代码对照', 0, '获取北交所股票代码变更后新旧代码映射表数据', '股票数据', '基础数据', 'bse_mapping', 120, '单次最大1000条（本接口总数据量300以内）', '0', 'tushare', 'bse_mapping', 0, 1006),
    ('tushare', 'bak_basic', '股票历史列表', 0, '获取备用基础列表，数据从2016年开始', '股票数据', '基础数据', 'bak_basic', 0, '单次最大7000条，可以根据日期参数循环获取历史，正式权限需要5000积分', '0', 'tushare', 'bak_basic', 0, 1007),
    ('tushare', 'rt_k', '实时日线', 0, '获取实时日k线行情，支持按股票代码及股票代码通配符一次性提取全部股票实时日k线行情', '股票数据', '行情数据', 'rt_k', 0, '单次最大可提取6000条数据，等同于一次提取全市场', '1', 'tushare', 'rt_k', 0, 1008),
    ('tushare', 'rt_min', '实时分钟', 0, '获取全A股票实时分钟数据，包括1~60min', '股票数据', '行情数据', 'rt_min', 0, '单次最大1000行数据，可以通过股票代码提取数据，支持逗号分隔的多个代码同时提取', '1', 'tushare', 'rt_min', 0, 1009),
    ('tushare', 'rt_min_daily', 'A股实时分钟-日累计', 0, '获取A股当日盘中历史分钟数据，可以提取单只股票当日开盘以来的所有分钟数据', '股票数据', '行情数据', 'rt_min_daily', 0, '', '1', 'tushare', 'rt_min_daily', 0, 1010),
    ('tushare', 'stk_weekly_monthly', '周/月线行情(每日更新)', 0, '股票周/月线行情(每日更新)', '股票数据', '行情数据', 'stk_weekly_monthly', 2000, '单次最大6000,可使用交易日期循环提取，总量不限制', '0', 'tushare', 'stk_weekly_monthly', 0, 1011),
    ('tushare', 'stk_week_month_adj', '周/月线复权行情(每日更新)', 0, '股票周/月线行情(复权--每日更新)', '股票数据', '行情数据', 'stk_week_month_adj', 2000, '单次最大6000,可使用交易日期循环提取，总量不限制', '0', 'tushare', 'stk_week_month_adj', 0, 1012),
    ('tushare', 'realtime_quote', '实时Tick（爬虫）', 0, '本接口是tushare org版实时接口的顺延，数据来自网络，且不进入tushare服务器，属于爬虫接口，请将tushare升级到1.3.3版本以上', '股票数据', '行情数据', 'realtime_quote', 0, '', '0', 'tushare', 'realtime_quote', 0, 1013),
    ('tushare', 'realtime_tick', '实时成交（爬虫）', 0, '本接口是tushare org版实时接口的顺延，数据来自网络，且不进入tushare服务器，属于爬虫接口，数据包括该股票当日开盘以来的所有分笔成交数据', '股票数据', '行情数据', 'realtime_tick', 0, '', '0', 'tushare', 'realtime_tick', 0, 1014),
    ('tushare', 'realtime_list', '实时排名（爬虫）', 0, '本接口是tushare org版实时接口的顺延，数据来自网络，且不进入tushare服务器，属于爬虫接口，数据包括该股票当日开盘以来的所有分笔成交数据', '股票数据', '行情数据', 'realtime_list', 0, '', '0', 'tushare', 'realtime_list', 0, 1015),
    ('tushare', 'ggt_top10', '港股通十大成交股', 0, '获取港股通每日成交数据，其中包括沪市、深市详细数据，每天18~20点之间完成当日更新', '股票数据', '行情数据', 'ggt_top10', 0, '', '0', 'tushare', 'ggt_top10', 0, 1016),
    ('tushare', 'ggt_daily', '港股通每日成交统计', 0, '获取港股通每日成交信息，数据从2014年开始', '股票数据', '行情数据', 'ggt_daily', 2000, '单次最大1000，总量数据不限制', '0', 'tushare', 'ggt_daily', 0, 1017),
    ('tushare', 'ggt_monthly', '港股通每月成交统计', 0, '港股通每月成交信息，数据从2014年开始', '股票数据', '行情数据', 'ggt_monthly', 5000, '单次最大1000', '0', 'tushare', 'ggt_monthly', 0, 1018),
    ('tushare', 'stk_shock', '个股异常波动', 0, '根据证券交易所交易规则的有关规定，交易所每日发布股票交易异常波动情况', '股票数据', '参考数据', 'stk_shock', 6000, '单次最大1000条，可根据代码或日期循环提取', '0', 'tushare', 'stk_shock', 0, 1019),
    ('tushare', 'stk_high_shock', '个股严重异常波动', 0, '根据证券交易所交易规则的有关规定，交易所每日发布股票交易严重异常波动情况', '股票数据', '参考数据', 'stk_high_shock', 6000, '单次最大1000条，可根据代码或日期循环提取', '0', 'tushare', 'stk_high_shock', 0, 1020),
    ('tushare', 'stk_alert', '交易所重点提示证券', 0, '根据证券交易所交易规则的有关规定，交易所每日发布重点提示证券', '股票数据', '参考数据', 'stk_alert', 6000, '单次最大1000条，可根据代码或日期循环提取', '0', 'tushare', 'stk_alert', 0, 1021),
    ('tushare', 'top10_floatholders', '前十大流通股东', 0, '获取上市公司前十大流通股东数据', '股票数据', '参考数据', 'top10_floatholders', 2000, '', '0', 'tushare', 'top10_floatholders', 0, 1022),
    ('tushare', 'stk_account', '股票开户数据（停）', 0, '获取股票账户开户数据，统计周期为一周', '股票数据', '参考数据', 'stk_account', 600, '', '0', 'tushare', 'stk_account', 0, 1023),
    ('tushare', 'stk_account_old', '股票开户数据（旧）', 0, '获取股票账户开户数据旧版格式数据，数据从2008年1月开始，到2015年5月29，新数据请通过', '股票数据', '参考数据', 'stk_account_old', 600, '', '0', 'tushare', 'stk_account_old', 0, 1024),
    ('tushare', 'stk_holdernumber', '股东人数', 0, '获取上市公司股东户数数据，数据不定期公布', '股票数据', '参考数据', 'stk_holdernumber', 600, '单次最大3000,总量不限制', '0', 'tushare', 'stk_holdernumber', 0, 1025),
    ('tushare', 'ccass_hold', '中央结算系统持股统计', 0, '获取中央结算系统持股汇总数据，覆盖全部历史数据，根据交易所披露时间，当日数据在下一交易日早上9点前完成入库', '股票数据', '特色数据', 'ccass_hold', 120, '单次最大5000条数据，可循环或分页提供全部', '0', 'tushare', 'ccass_hold', 0, 1026),
    ('tushare', 'ccass_hold_detail', '中央结算系统持股明细', 0, '获取中央结算系统机构席位持股明细，数据覆盖', '股票数据', '特色数据', 'ccass_hold_detail', 8000, '单次最大返回6000条数据，可以循环或分页提取', '0', 'tushare', 'ccass_hold_detail', 0, 1027),
    ('tushare', 'stk_auction_o', '股票开盘集合竞价数据', 0, '股票开盘9:30集合竞价数据，每天盘后更新', '股票数据', '特色数据', 'stk_auction_o', 0, '单次请求最大返回10000行数据，可根据日期循环', '1', 'tushare', 'stk_auction_o', 0, 1028),
    ('tushare', 'stk_auction_c', '股票收盘集合竞价数据', 0, '股票收盘15:00集合竞价数据，每天盘后更新', '股票数据', '特色数据', 'stk_auction_c', 0, '单次请求最大返回10000行数据，可根据日期循环', '1', 'tushare', 'stk_auction_c', 0, 1029),
    ('tushare', 'stk_nineturn', '神奇九转指标', 0, '神奇九转（又称“九转序列”）是一种基于技术分析的股票趋势反转指标，其思想来源于技术分析大师汤姆·迪马克（Tom DeMark）的TD序列。该指标的核心功能是通过识别股价在上涨或下跌过程中连续9天的特定走势，来判断股价的潜在反转点，从而帮助投资者提高抄底和逃顶的成功率，日线级别配合60min的九转效果更好，数据从20230101开始', '股票数据', '特色数据', 'stk_nineturn', 6000, '单次提取最大返回10000行数据，可通过股票代码和日期循环获取全部数据', '0', 'tushare', 'stk_nineturn', 0, 1030),
    ('tushare', 'stk_ah_comparison', 'AH股比价', 0, 'AH股比价数据，可根据交易日期获取历史', '股票数据', '特色数据', 'stk_ah_comparison', 5000, '', '0', 'tushare', 'stk_ah_comparison', 0, 1031),
    ('tushare', 'stk_surv', '机构调研数据', 0, '获取上市公司机构调研记录数据', '股票数据', '特色数据', 'stk_surv', 5000, '单次最大获取100条数据，可循环或分页提取', '0', 'tushare', 'stk_surv', 0, 1032),
    ('tushare', 'broker_recommend', '券商月度金股', 0, '获取券商月度金股，一般1日~3日内更新当月数据', '股票数据', '特色数据', 'broker_recommend', 6000, '单次最大1000行数据，可循环提取', '0', 'tushare', 'broker_recommend', 0, 1033),
    ('tushare', 'margin_secs', '融资融券标的（盘前）', 0, '获取沪深京三大交易所融资融券标的（包括ETF），每天盘前更新', '股票数据', '两融及转融通', 'margin_secs', 2000, '单次最大6000行数据，可根据股票代码、交易日期、交易所代码循环提取', '0', 'tushare', 'margin_secs', 0, 1034),
    ('tushare', 'slb_sec', '转融券交易汇总(停）', 0, '转融通转融券交易汇总', '股票数据', '两融及转融通', 'slb_sec', 2000, '单次最大可以提取5000行数据，可循环获取所有历史', '0', 'tushare', 'slb_sec', 0, 1035),
    ('tushare', 'slb_len', '转融资交易汇总', 0, '转融通融资汇总', '股票数据', '两融及转融通', 'slb_len', 2000, '单次最大可以提取5000行数据，可循环获取所有历史', '0', 'tushare', 'slb_len', 0, 1036),
    ('tushare', 'slb_sec_detail', '转融券交易明细(停）', 0, '转融券交易明细', '股票数据', '两融及转融通', 'slb_sec_detail', 2000, '单次最大可以提取5000行数据，可循环获取所有历史', '0', 'tushare', 'slb_sec_detail', 0, 1037),
    ('tushare', 'slb_len_mm', '做市借券交易汇总(停）', 0, '做市借券交易汇总', '股票数据', '两融及转融通', 'slb_len_mm', 2000, '单次最大可以提取5000行数据，可循环获取所有历史', '0', 'tushare', 'slb_len_mm', 0, 1038),
    ('tushare', 'moneyflow_ths', '个股资金流向（THS）', 0, '获取同花顺个股资金流向数据，每日盘后更新', '股票数据', '资金流向数据', 'moneyflow_ths', 6000, '单次最大6000，可根据日期或股票代码循环提取数据', '0', 'tushare', 'moneyflow_ths', 0, 1039),
    ('tushare', 'moneyflow_dc', '个股资金流向（DC）', 0, '获取东方财富个股资金流向数据，每日盘后更新，数据开始于20230911', '股票数据', '资金流向数据', 'moneyflow_dc', 5000, '单次最大获取6000条数据，可根据日期或股票代码循环提取数据', '0', 'tushare', 'moneyflow_dc', 0, 1040),
    ('tushare', 'moneyflow_cnt_ths', '板块资金流向（THS)', 0, '获取同花顺概念板块每日资金流向', '股票数据', '资金流向数据', 'moneyflow_cnt_ths', 6000, '单次最大可调取5000条数据，可以根据日期和代码循环提取全部数据', '0', 'tushare', 'moneyflow_cnt_ths', 0, 1041),
    ('tushare', 'moneyflow_ind_ths', '行业资金流向（THS）', 0, '获取同花顺行业资金流向，每日盘后更新', '股票数据', '资金流向数据', 'moneyflow_ind_ths', 6000, '单次最大可调取5000条数据，可以根据日期和代码循环提取全部数据', '0', 'tushare', 'moneyflow_ind_ths', 0, 1042),
    ('tushare', 'moneyflow_ind_dc', '板块资金流向（DC）', 0, '获取东方财富板块资金流向，每天盘后更新', '股票数据', '资金流向数据', 'moneyflow_ind_dc', 6000, '单次最大可调取5000条数据，可以根据日期和代码循环提取全部数据', '0', 'tushare', 'moneyflow_ind_dc', 0, 1043),
    ('tushare', 'moneyflow_mkt_dc', '大盘资金流向（DC）', 0, '获取东方财富大盘资金流向数据，每日盘后更新', '股票数据', '资金流向数据', 'moneyflow_mkt_dc', 120, '单次最大3000条，可根据日期或日期区间循环获取', '0', 'tushare', 'moneyflow_mkt_dc', 0, 1044),
    ('tushare', 'moneyflow_hsgt', '沪深港通资金流向', 0, '获取沪股通、深股通、港股通每日资金流向数据，每次最多返回300条记录，总量不限制', '股票数据', '资金流向数据', 'moneyflow_hsgt', 0, '', '0', 'tushare', 'moneyflow_hsgt', 0, 1045),
    ('tushare', 'limit_list_ths', '同花顺涨跌停榜单', 0, '获取同花顺每日涨跌停榜单数据，历史数据从20231101开始提供，增量每天16点左右更新', '股票数据', '打板专题数据', 'limit_list_ths', 8000, '单次最大4000条，可根据日期或股票代码循环提取', '0', 'tushare', 'limit_list_ths', 0, 1046),
    ('tushare', 'limit_step', '涨停股票连板天梯', 0, '获取每天连板个数晋级的股票，可以分析出每天连续涨停进阶个数，判断强势热度', '股票数据', '打板专题数据', 'limit_step', 8000, '单次最大2000行数据，可根据股票代码或者日期循环提取全部', '0', 'tushare', 'limit_step', 0, 1047),
    ('tushare', 'limit_cpt_list', '涨停最强板块统计', 0, '获取每天涨停股票最多最强的概念板块，可以分析强势板块的轮动，判断资金动向', '股票数据', '打板专题数据', 'limit_cpt_list', 8000, '单次最大2000行数据，可根据股票代码或者日期循环提取全部', '0', 'tushare', 'limit_cpt_list', 0, 1048),
    ('tushare', 'ths_index', '同花顺行业概念板块', 0, '获取同花顺板块指数，包括概念、行业、特色指数', '股票数据', '打板专题数据', 'ths_index', 6000, '单次最大返回5000行数据', '0', 'tushare', 'ths_index', 0, 1049),
    ('tushare', 'ths_daily', '同花顺概念和行业指数行情', 0, '获取同花顺板块指数行情', '股票数据', '打板专题数据', 'ths_daily', 0, '单次最大3000行数据（需6000积分），可根据指数代码、日期参数循环提取', '0', 'tushare', 'ths_daily', 0, 1050),
    ('tushare', 'ths_member', '同花顺行业概念成分', 0, '获取同花顺概念板块成分列表', '股票数据', '打板专题数据', 'ths_member', 0, '用户积累6000积分可调取，每分钟可调取200次，可按概念板块代码循环提取所有成分', '0', 'tushare', 'ths_member', 0, 1051),
    ('tushare', 'dc_index', '东方财富概念板块', 0, '获取东方财富每个交易日的概念板块数据，支持按日期查询', '股票数据', '打板专题数据', 'dc_index', 6000, '单次最大可获取5000条数据，历史数据可根据日期循环获取', '0', 'tushare', 'dc_index', 0, 1052),
    ('tushare', 'dc_daily', '东财概念和行业指数行情', 0, '获取东财概念板块、行业指数板块、地域板块行情数据，历史数据开始于2020年', '股票数据', '打板专题数据', 'dc_daily', 6000, '单次最大2000条数据，可根据日期参数循环获取', '0', 'tushare', 'dc_daily', 0, 1053),
    ('tushare', 'stk_auction', '开盘竞价成交（当日）', 0, '获取当日个股和ETF的集合竞价成交情况，每天9点25~29分之间可以获取当日的集合竞价成交数据', '股票数据', '打板专题数据', 'stk_auction', 0, '单次最大返回8000行数据，可根据日期或代码循环获取历史', '1', 'tushare', 'stk_auction', 0, 1054),
    ('tushare', 'hm_list', '市场游资最全名录', 0, '获取游资分类名录信息', '股票数据', '打板专题数据', 'hm_list', 5000, '单次最大1000条数据，目前总量未超过500', '0', 'tushare', 'hm_list', 0, 1055),
    ('tushare', 'hm_detail', '游资交易每日明细', 0, '获取每日游资交易明细，数据开始于2022年8。游资分类名录，请点击', '股票数据', '打板专题数据', 'hm_detail', 10000, '单次最多提取2000条记录，可循环调取，总量不限制', '0', 'tushare', 'hm_detail', 0, 1056),
    ('tushare', 'ths_hot', '同花顺App热榜数', 0, '获取同花顺App热榜数据，包括热股、概念板块、ETF、可转债、港美股等等，每日盘中提取4次，收盘后4次，最晚22点提取一次', '股票数据', '打板专题数据', 'ths_hot', 6000, '单次最大2000条，可根据日期等参数循环获取全部数据', '0', 'tushare', 'ths_hot', 0, 1057),
    ('tushare', 'tdx_index', '通达信板块信息', 0, '获取通达信板块基础信息，包括概念板块、行业、风格、地域等', '股票数据', '打板专题数据', 'tdx_index', 6000, '单次最大1000条数据，可根据日期参数循环提取', '0', 'tushare', 'tdx_index', 0, 1058),
    ('tushare', 'tdx_member', '通达信板块成分', 0, '获取通达信各板块成分股信息', '股票数据', '打板专题数据', 'tdx_member', 6000, '单次最大3000条数据，可以根据日期和板块代码循环提取', '0', 'tushare', 'tdx_member', 0, 1059),
    ('tushare', 'tdx_daily', '通达信板块行情', 0, '获取通达信各板块行情，包括成交和估值等数据', '股票数据', '打板专题数据', 'tdx_daily', 6000, '单次提取最大3000条数据，可根据板块代码和日期参数循环提取', '0', 'tushare', 'tdx_daily', 0, 1060),
    ('tushare', 'kpl_concept_cons', '题材成分（开盘啦）', 0, '获取开盘啦概念题材的成分股', '股票数据', '打板专题数据', 'kpl_concept_cons', 5000, '单次最大3000条，可根据代码和日期循环获取全部数据', '0', 'tushare', 'kpl_concept_cons', 0, 1061),
    ('tushare', 'dc_concept', '题材数据（东方财富）', 0, '获取东财概念题材列表，每天盘后更新', '股票数据', '打板专题数据', 'dc_concept', 6000, '单次最大5000，可根据日期循环获取历史数据,（数据从20260203开始）', '0', 'tushare', 'dc_concept', 0, 1062),
    ('tushare', 'dc_concept_cons', '题材成分（东方财富）', 0, '获取东方财富概念题材的成分股，每天盘后更新', '股票数据', '打板专题数据', 'dc_concept_cons', 6000, '单次最大3000，可根据日期循环获取历史数据,（数据从20260203开始）', '0', 'tushare', 'dc_concept_cons', 0, 1063),
    ('tushare', 'rt_idx_k', '指数实时日线', 0, '获取交易所指数实时日线行情，支持按代码或代码通配符一次性提取全部交易所指数实时日k线行情', '指数数据', '指数实时日线', 'rt_idx_k', 0, '', '1', 'tushare', 'rt_idx_k', 0, 1064),
    ('tushare', 'rt_idx_min', '指数实时分钟', 0, '获取交易所指数实时分钟数据，包括1~60min', '指数数据', '指数实时分钟', 'rt_idx_min', 0, '单次最大1000行数据，可以通过股票代码提取数据，支持逗号分隔的多个代码同时提取', '1', 'tushare', 'rt_idx_min', 0, 1065),
    ('tushare', 'idx_mins', '指数历史分钟', 0, '获取交易所指数分钟数据，支持1min/5min/15min/30min/60min行情，提供Python SDK和 http Restful API两种方式', '指数数据', '指数历史分钟', 'idx_mins', 0, '单次最大8000行数据，可以通过指数代码和时间循环获取，本接口可以提供超过10年历史分钟数据', '1', 'tushare', 'idx_mins', 0, 1066),
    ('tushare', 'sw_daily', '申万行业指数日行情', 0, '获取申万行业日线行情（默认是申万2021版行情）', '指数数据', '申万行业指数日行情', 'sw_daily', 0, '单次最大4000行数据，可通过指数代码和日期参数循环提取，5000积分可调取', '0', 'tushare', 'sw_daily', 0, 1067),
    ('tushare', 'rt_sw_k', '申万实时行情', 0, '获取申万行业指数的最新截面数据', '指数数据', '申万实时行情', 'rt_sw_k', 0, '', '1', 'tushare', 'rt_sw_k', 0, 1068),
    ('tushare', 'ci_index_member', '中信行业成分', 0, '按三级分类提取中信行业成分，可提供某个分类的所有成分，也可按股票代码提取所属分类，参数灵活', '指数数据', '中信行业成分', 'ci_index_member', 5000, '单次最大5000行，总量不限制', '0', 'tushare', 'ci_index_member', 0, 1069),
    ('tushare', 'ci_daily', '中信行业指数日行情', 0, '获取中信行业指数日线行情', '指数数据', '中信行业指数日行情', 'ci_daily', 5000, '单次最大4000条，可循环提取', '0', 'tushare', 'ci_daily', 0, 1070),
    ('tushare', 'idx_factor_pro', '指数技术面因子(专业版)', 0, '获取指数每日技术面因子数据，用于跟踪指数当前走势情况，数据由Tushare社区自产，覆盖全历史；输出参数_bfq表示不复权描述中说明了因子的默认传参，如需要特殊参数或者更多因子可以联系管理员评估，指数包括大盘指数 申万行业指数 中信指数', '指数数据', '指数技术面因子(专业版)', 'idx_factor_pro', 5000, '单次最大8000', '0', 'tushare', 'idx_factor_pro', 0, 1071),
    ('tushare', 'sz_daily_info', '深圳市场每日交易情况', 0, '获取深圳市场每日交易概况', '指数数据', '深圳市场每日交易情况', 'sz_daily_info', 2000, '单次最大2000，可循环获取，总量不限制', '0', 'tushare', 'sz_daily_info', 0, 1072),
    ('tushare', 'etf_basic', 'ETF基本信息', 0, '获取国内ETF基础信息，包括了QDII。数据来源与沪深交易所公开披露信息', 'ETF专题', 'ETF基本信息', 'etf_basic', 8000, '单次请求最大放回5000条数据（当前ETF总数未超过2000）', '0', 'tushare', 'etf_basic', 0, 1073),
    ('tushare', 'etf_index', 'ETF基准指数', 0, '获取ETF基准指数列表信息', 'ETF专题', 'ETF基准指数', 'etf_index', 8000, '单次请求最大返回5000行数据（当前未超过2000个）', '0', 'tushare', 'etf_index', 0, 1074),
    ('tushare', 'etf_share_size', 'ETF份额规模', 0, '获取沪深ETF每日份额和规模数据，能体现规模份额的变化，掌握ETF资金动向，同时提供每日净值和收盘价；数据指标是分批入库，建议在每日19点后提取；另外，涉及海外的ETF数据更新会晚一些属于正常情况', 'ETF专题', 'ETF份额规模', 'etf_share_size', 8000, '单次最大5000条，可根据代码或日期循环提取', '0', 'tushare', 'etf_share_size', 0, 1075),
    ('tushare', 'rt_etf_sz_iopv', 'ETF实时参考', 0, 'ETF实时净值和申购赎回数据参考，目前只提供深市', 'ETF专题', 'ETF实时参考', 'rt_etf_sz_iopv', 0, '单次最大5000条，完全覆盖当前总量', '1', 'tushare', 'rt_etf_sz_iopv', 0, 1076),
    ('tushare', 'fund_manager', '基金经理', 0, '获取公募基金经理数据，包括基金经理简历等数据', '公募基金', '基金经理', 'fund_manager', 500, '单次最大5000，支持分页提取数据', '0', 'tushare', 'fund_manager', 0, 1077),
    ('tushare', 'fund_factor_pro', '基金技术面因子(专业版)', 0, '获取场内基金每日技术面因子数据，用于跟踪场内基金当前走势情况，数据由Tushare社区自产，覆盖全历史；输出参数_bfq表示不复权，描述中说明了因子的默认传参，如需要特殊参数或者更多因子可以联系管理员评估', '公募基金', '基金技术面因子(专业版)', 'fund_factor_pro', 5000, '单次最大8000', '0', 'tushare', 'fund_factor_pro', 0, 1078),
    ('tushare', 'fut_weekly_monthly', '期货周/月线行情(每日更新)', 0, '期货周/月线行情(每日更新)', '期货数据', '期货周/月线行情(每日更新)', 'fut_weekly_monthly', 0, '单次最大6000', '0', 'tushare', 'fut_weekly_monthly', 0, 1079),
    ('tushare', 'rt_fut_min', '实时分钟行情', 0, '获取全市场期货合约实时分钟数据，支持1min/5min/15min/30min/60min行情，提供Python SDK、 http Restful API和websocket三种方式，如果需要主力合约分钟，请先通过主力', '期货数据', '实时分钟行情', 'rt_fut_min', 0, '每分钟可以请求500次，支持多个合约同时提取', '1', 'tushare', 'rt_fut_min', 0, 1080),
    ('tushare', 'fut_weekly_detail', '期货主要品种交易周报', 0, '获取期货交易所主要品种每周交易统计信息，数据从2010年3月开始', '期货数据', '期货主要品种交易周报', 'fut_weekly_detail', 600, '单次最大获取4000行数据', '0', 'tushare', 'fut_weekly_detail', 0, 1081),
    ('tushare', 'ft_limit', '期货合约涨跌停价格', 0, '获取所有期货合约每天的涨跌停价格及最低保证金率，数据开始于2005年', '期货数据', '期货合约涨跌停价格', 'ft_limit', 5000, '单次最大获取4000行数据，可以通过日期、合约代码等参数循环获取所有历史', '0', 'tushare', 'ft_limit', 0, 1082),
    ('tushare', 'sge_basic', '上海黄金基础信息', 0, '获取上海黄金交易所现货合约基础信息', '现货数据', '上海黄金基础信息', 'sge_basic', 5000, '单次最大100条，当前现货合约数不足20个，可以一次提取全部，不需要循环提取', '0', 'tushare', 'sge_basic', 0, 1083),
    ('tushare', 'sge_daily', '上海黄金现货日行情', 0, '获取上海黄金交易所现货合约日线行情', '现货数据', '上海黄金现货日行情', 'sge_daily', 2000, '单次最大2000，可循环或者分页提取', '0', 'tushare', 'sge_daily', 0, 1084),
    ('tushare', 'cb_call', '可转债赎回信息', 0, '获取可转债到期赎回、强制赎回等信息。数据来源于公开披露渠道，供个人和机构研究使用，请不要用于数据商业目的', '债券专题', '可转债赎回信息', 'cb_call', 0, '单次最大2000条数据，可以根据日期循环提取，本接口需5000积分', '0', 'tushare', 'cb_call', 0, 1085),
    ('tushare', 'cb_rate', '可转债票面利率', 0, '获取可转债票面利率', '债券专题', '可转债票面利率', 'cb_rate', 5000, '单次最大2000，总量不限制', '0', 'tushare', 'cb_rate', 0, 1086),
    ('tushare', 'cb_factor_pro', '可转债技术面因子(专业版)', 0, '获取可转债每日技术面因子数据，用于跟踪可转债当前走势情况，数据由Tushare社区自产，覆盖全历史；输出参数_bfq表示不复权，_qfq表示前复权 _hfq表示后复权，描述中说明了因子的默认传参，如需要特殊参数或者更多因子可以联系管理员评估', '债券专题', '可转债技术面因子(专业版)', 'cb_factor_pro', 5000, '单次调取最多返回10000条数据，可以通过日期参数循环', '0', 'tushare', 'cb_factor_pro', 0, 1087),
    ('tushare', 'cb_price_chg', '可转债转股价变动', 0, '获取可转债转股价变动', '债券专题', '可转债转股价变动', 'cb_price_chg', 0, '单次最大2000，总量不限制', '1', 'tushare', 'cb_price_chg', 0, 1088),
    ('tushare', 'cb_rating', '可转债债券评级', 0, '获取可转债评级历史记录', '债券专题', '可转债债券评级', 'cb_rating', 2000, '单次最大3000条，可根据代码或日期循环提取', '0', 'tushare', 'cb_rating', 0, 1089),
    ('tushare', 'repo_daily', '债券回购日行情', 0, '债券回购日行情', '债券专题', '债券回购日行情', 'repo_daily', 2000, '单次最大2000条，可多次提取，总量不限制', '0', 'tushare', 'repo_daily', 0, 1090),
    ('tushare', 'bc_otcqt', '柜台流通式债券报价', 0, '柜台流通式债券报价', '债券专题', '柜台流通式债券报价', 'bc_otcqt', 500, '单次最大2000条，可多次提取，总量不限制', '0', 'tushare', 'bc_otcqt', 0, 1091),
    ('tushare', 'bc_bestotcqt', '柜台流通式债券最优报价', 0, '柜台流通式债券最优报价', '债券专题', '柜台流通式债券最优报价', 'bc_bestotcqt', 500, '单次最大2000，可多次提取，总量不限制', '0', 'tushare', 'bc_bestotcqt', 0, 1092),
    ('tushare', 'bond_blk', '大宗交易', 0, '获取沪深交易所债券大宗交易数据', '债券专题', '大宗交易', 'bond_blk', 0, '单次最大1000条', '1', 'tushare', 'bond_blk', 0, 1093),
    ('tushare', 'bond_blk_detail', '大宗交易明细', 0, '获取沪深交易所债券大宗交易数据', '债券专题', '大宗交易明细', 'bond_blk_detail', 0, '单次最大1000条', '1', 'tushare', 'bond_blk_detail', 0, 1094),
    ('tushare', 'yc_cb', '国债收益率曲线', 0, '获取中债收益率曲线，目前可获取中债国债收益率曲线即期和到期收益率曲线数据', '债券专题', '国债收益率曲线', 'yc_cb', 0, '单次最大2000，总量不限制，可循环提取', '1', 'tushare', 'yc_cb', 0, 1095),
    ('tushare', 'eco_cal', '全球财经事件', 0, '获取全球财经日历、包括经济事件数据更新', '债券专题', '全球财经事件', 'eco_cal', 2000, '单次最大获取100行数据', '0', 'tushare', 'eco_cal', 0, 1096),
    ('tushare', 'hk_tradecal', '港股交易日历', 0, '获取交易日历', '港股数据', '港股交易日历', 'hk_tradecal', 2000, '单次最大2000', '0', 'tushare', 'hk_tradecal', 0, 1097),
    ('tushare', 'hk_daily_adj', '港股复权行情', 0, '获取港股复权行情，提供股票股本、市值和成交及换手多个数据指标', '港股数据', '港股复权行情', 'hk_daily_adj', 0, '单次最大可以提取6000条数据，可循环获取全部，支持分页提取', '0', 'tushare', 'hk_daily_adj', 0, 1098),
    ('tushare', 'hk_adjfactor', '港股复权因子', 0, '获取港股每日复权因子数据，每天滚动刷新', '港股数据', '港股复权因子', 'hk_adjfactor', 0, '单次最大6000行数据，可以根据日期循环', '1', 'tushare', 'hk_adjfactor', 0, 1099),
    ('tushare', 'hk_income', '港股利润表', 0, '获取港股上市公司财务利润表数据', '港股数据', '港股利润表', 'hk_income', 15000, '', '0', 'tushare', 'hk_income', 0, 1100),
    ('tushare', 'hk_balancesheet', '港股资产负债表', 0, '获取港股上市公司资产负债表', '港股数据', '港股资产负债表', 'hk_balancesheet', 15000, '', '0', 'tushare', 'hk_balancesheet', 0, 1101),
    ('tushare', 'hk_cashflow', '港股现金流量表', 0, '获取港股上市公司现金流量表数据', '港股数据', '港股现金流量表', 'hk_cashflow', 15000, '', '0', 'tushare', 'hk_cashflow', 0, 1102),
    ('tushare', 'hk_fina_indicator', '港股财务指标数据', 0, '获取港股上市公司财务指标数据，为避免服务器压力，现阶段每次请求最多返回200条记录，可通过设置日期多次请求获取更多数据', '港股数据', '港股财务指标数据', 'hk_fina_indicator', 15000, '', '0', 'tushare', 'hk_fina_indicator', 0, 1103),
    ('tushare', 'us_tradecal', '美股交易日历', 0, '获取美股交易日历信息', '美股数据', '美股交易日历', 'us_tradecal', 0, '单次最大6000，可根据日期阶段获取', '0', 'tushare', 'us_tradecal', 0, 1104),
    ('tushare', 'us_daily_adj', '美股复权行情', 0, '获取美股复权行情，支持美股全市场股票，提供股本、市值、复权因子和成交信息等多个数据指标', '美股数据', '美股复权行情', 'us_daily_adj', 0, '单次最大可以提取8000条数据，可循环获取全部，支持分页提取', '0', 'tushare', 'us_daily_adj', 0, 1105),
    ('tushare', 'us_adjfactor', '美股复权因子', 0, '获取美股每日复权因子数据，在每天美股收盘后滚动刷新', '美股数据', '美股复权因子', 'us_adjfactor', 0, '单次最大15000行数据，可以根据日期循环', '1', 'tushare', 'us_adjfactor', 0, 1106),
    ('tushare', 'us_income', '美股利润表', 0, '获取美股上市公司财务利润表数据（目前只覆盖主要美股和中概股）', '美股数据', '美股利润表', 'us_income', 15000, '', '0', 'tushare', 'us_income', 0, 1107),
    ('tushare', 'us_balancesheet', '美股资产负债表', 0, '获取美股上市公司资产负债表（目前只覆盖主要美股和中概股）', '美股数据', '美股资产负债表', 'us_balancesheet', 15000, '', '0', 'tushare', 'us_balancesheet', 0, 1108),
    ('tushare', 'us_cashflow', '美股现金流量表', 0, '获取美股上市公司现金流量表数据（目前只覆盖主要美股和中概股）', '美股数据', '美股现金流量表', 'us_cashflow', 15000, '', '0', 'tushare', 'us_cashflow', 0, 1109),
    ('tushare', 'us_fina_indicator', '美股财务指标数据', 0, '获取美股上市公司财务指标数据，目前只覆盖主要美股和中概股。为避免服务器压力，现阶段每次请求最多返回200条记录，可通过设置日期多次请求获取更多数据', '美股数据', '美股财务指标数据', 'us_fina_indicator', 15000, '', '0', 'tushare', 'us_fina_indicator', 0, 1110),
    ('tushare', 'tmt_twincome', '台湾电子产业月营收', 0, '获取台湾TMT电子产业领域各类产品月度营收数据', '行业经济', 'TMT行业', 'tmt_twincome', 0, '', '0', 'tushare', 'tmt_twincome', 0, 1111),
    ('tushare', 'tmt_twincomedetail', '台湾电子产业月营收明细', 0, '获取台湾TMT行业上市公司各类产品月度营收情况', '行业经济', 'TMT行业', 'tmt_twincomedetail', 0, '', '0', 'tushare', 'tmt_twincomedetail', 0, 1112),
    ('tushare', 'bo_daily', '电影日度票房', 0, '获取电影日度票房', '行业经济', 'TMT行业', 'bo_daily', 0, '', '0', 'tushare', 'bo_daily', 0, 1113),
    ('tushare', 'bo_cinema', '影院日度票房', 0, '获取每日各影院的票房数据', '行业经济', 'TMT行业', 'bo_cinema', 0, '', '0', 'tushare', 'bo_cinema', 0, 1114),
    ('tushare', 'film_record', '全国电影剧本备案数据', 0, '获取全国电影剧本备案的公示数据', '行业经济', 'TMT行业', 'film_record', 0, '单次最大500，总量不限制', '0', 'tushare', 'film_record', 0, 1115),
    ('tushare', 'teleplay_record', '全国电视剧备案公示数据', 0, '获取2009年以来全国拍摄制作电视剧备案公示数据', '行业经济', 'TMT行业', 'teleplay_record', 0, '单次最大1000，总量不限制', '0', 'tushare', 'teleplay_record', 0, 1116),
    ('tushare', 'shibor_quote', 'Shibor报价数据', 0, 'Shibor报价数据', '宏观经济', '国内宏观', 'shibor_quote', 120, '单次最大4000行数据，总量不限制，可通过设置开始和结束日期分段获取', '0', 'tushare', 'shibor_quote', 0, 1117),
    ('tushare', 'libor', 'Libor利率', 0, 'Libor拆借利率', '宏观经济', '国内宏观', 'libor', 120, '单次最大4000行数据，总量不限制，可通过设置开始和结束日期分段获取', '0', 'tushare', 'libor', 0, 1118),
    ('tushare', 'hibor', 'Hibor利率', 0, 'Hibor利率', '宏观经济', '国内宏观', 'hibor', 120, '单次最大4000行数据，总量不限制，可通过设置开始和结束日期分段获取', '0', 'tushare', 'hibor', 0, 1119),
    ('tushare', 'wz_index', '温州民间借贷利率', 0, '温州民间借贷利率，即温州指数', '宏观经济', '国内宏观', 'wz_index', 2000, '不限量，一次可取全部指标全部历史数据', '0', 'tushare', 'wz_index', 0, 1120),
    ('tushare', 'gz_index', '广州民间借贷利率', 0, '广州民间借贷利率', '宏观经济', '国内宏观', 'gz_index', 2000, '不限量，一次可取全部指标全部历史数据', '0', 'tushare', 'gz_index', 0, 1121),
    ('tushare', 'cn_ppi', '工业生产者出厂价格指数（PPI）', 0, '获取PPI工业生产者出厂价格指数数据', '宏观经济', '国内宏观', 'cn_ppi', 600, '单次最大5000，一次可以提取全部数据', '0', 'tushare', 'cn_ppi', 0, 1122),
    ('tushare', 'cn_m', '货币供应量（月）', 0, '获取货币供应量之月度数据', '宏观经济', '国内宏观', 'cn_m', 600, '单次最大5000，一次可以提取全部数据', '0', 'tushare', 'cn_m', 0, 1123),
    ('tushare', 'sf_month', '社融增量（月度）', 0, '获取月度社会融资数据', '宏观经济', '国内宏观', 'sf_month', 2000, '单次最大2000条数据，可循环提取', '0', 'tushare', 'sf_month', 0, 1124),
    ('tushare', 'cn_pmi', '采购经理指数（PMI）', 0, '采购经理人指数', '宏观经济', '国内宏观', 'cn_pmi', 2000, '单次最大2000，一次可以提取全部数据', '0', 'tushare', 'cn_pmi', 0, 1125),
    ('tushare', 'us_tycr', '国债收益率曲线利率', 0, '获取美国每日国债收益率曲线利率', '宏观经济', '国际宏观', 'us_tycr', 120, '单次最大可获取2000条数据', '0', 'tushare', 'us_tycr', 0, 1126),
    ('tushare', 'us_trycr', '国债实际收益率曲线利率', 0, '国债实际收益率曲线利率', '宏观经济', '国际宏观', 'us_trycr', 120, '单次最大可获取2000行数据，可循环获取', '0', 'tushare', 'us_trycr', 0, 1127),
    ('tushare', 'us_tbr', '短期国债利率', 0, '获取美国短期国债利率数据', '宏观经济', '国际宏观', 'us_tbr', 120, '单次最大可获取2000行数据，可循环获取', '0', 'tushare', 'us_tbr', 0, 1128),
    ('tushare', 'us_tltr', '国债长期利率', 0, '国债长期利率', '宏观经济', '国际宏观', 'us_tltr', 120, '单次最大可获取2000行数据，可循环获取', '0', 'tushare', 'us_tltr', 0, 1129),
    ('tushare', 'us_trltr', '国债长期利率平均值', 0, '国债实际长期利率平均值', '宏观经济', '国际宏观', 'us_trltr', 120, '单次最大可获取2000行数据，可循环获取', '0', 'tushare', 'us_trltr', 0, 1130),
    ('tushare', 'npr', '国家政策库', 0, '获取国家行政机关公开披露的各类法规、条例政策、批复、通知等文本数据', '资讯数据', '国家政策库', 'npr', 0, '单次最大500条，可根据参数循环提取', '1', 'tushare', 'npr', 0, 1131),
    ('tushare', 'research_report', '券商研究报告', 0, '获取券商研究报告-个股、行业等，历史数据从20170101开始提供，增量每天两次更新', '资讯数据', '券商研究报告', 'research_report', 0, '单次最大1000条，可根据日期或券商名称代码循环提取，每天总量不限制', '1', 'tushare', 'research_report', 0, 1132),
    ('tushare', 'anns_d', '上市公司公告', 0, '获取全量公告数据，提供pdf下载URL', '资讯数据', '上市公司公告', 'anns_d', 0, '单次最大2000条数，可以跟进日期循环获取全量', '1', 'tushare', 'anns_d', 0, 1133),
    ('tushare', 'fund_sales_ratio', '各渠道公募基金销售保有规模占比', 0, '获取各渠道公募基金销售保有规模占比数据，年度更新', '财富管理', '基金销售行业数据', 'fund_sales_ratio', 0, '单次最大100行数据，数据从2015年开始公布，当前数据量很小', '0', 'tushare', 'fund_sales_ratio', 0, 1134),
    ('tushare', 'fund_sales_vol', '销售机构公募基金销售保有规模', 0, '获取销售机构公募基金销售保有规模数据，本数据从2021年Q1开始公布，季度更新', '财富管理', '基金销售行业数据', 'fund_sales_vol', 0, '单次最大500行数据，目前总量只有100行，未来随着数据量增加会提高上限', '0', 'tushare', 'fund_sales_vol', 0, 1135);

INSERT INTO `quantmate`.`data_source_items`
  (`source`, `item_key`, `item_name`, `enabled`, `description`, `category`, `sub_category`, `api_name`, `permission_points`, `rate_limit_note`, `requires_permission`, `target_database`, `target_table`, `table_created`, `sync_priority`)
SELECT
  `source`, `item_key`, `item_name`, `enabled`, `description`, `category`, `sub_category`, `api_name`, `permission_points`, `rate_limit_note`, `requires_permission`, `target_database`, `target_table`, `table_created`, `sync_priority`
FROM `_tmp_tushare_catalog_refresh`
ON DUPLICATE KEY UPDATE
  item_name = VALUES(item_name),
  description = VALUES(description),
  category = VALUES(category),
  sub_category = VALUES(sub_category),
  api_name = VALUES(api_name),
  permission_points = VALUES(permission_points),
  rate_limit_note = VALUES(rate_limit_note),
  requires_permission = VALUES(requires_permission),
  target_database = VALUES(target_database),
  target_table = VALUES(target_table),
  sync_priority = VALUES(sync_priority);

DELETE dsi
FROM `quantmate`.`data_source_items` dsi
LEFT JOIN `_tmp_tushare_catalog_refresh` tmp
  ON BINARY tmp.source = BINARY dsi.source
 AND BINARY tmp.item_key = BINARY dsi.item_key
WHERE dsi.source = 'tushare'
  AND tmp.item_key IS NULL;

DELETE ssi
FROM `quantmate`.`sync_status_init` ssi
LEFT JOIN `_tmp_tushare_catalog_refresh` tmp
  ON BINARY tmp.source = BINARY ssi.source
 AND BINARY tmp.item_key = BINARY ssi.interface_key
WHERE ssi.source = 'tushare'
  AND tmp.item_key IS NULL;

DELETE dss
FROM `quantmate`.`data_sync_status` dss
LEFT JOIN `_tmp_tushare_catalog_refresh` tmp
  ON BINARY tmp.source = BINARY dss.source
 AND BINARY tmp.item_key = BINARY dss.interface_key
WHERE dss.source = 'tushare'
  AND tmp.item_key IS NULL;

DROP TEMPORARY TABLE `_tmp_tushare_catalog_refresh`;
