"""RD-Agent Sidecar — thin Flask wrapper around rdagent CLI.

Accepts mining requests from QuantMate's RQ worker and executes the
RD-Agent R&D loop. Returns iteration results and discovered factors.
"""

from __future__ import annotations

import json
import logging
import os
import re
import signal
import subprocess
import sys
import threading
import time
import traceback
from pathlib import Path

import pandas as pd
from flask import Flask, jsonify, request

app = Flask(__name__)
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("rdagent-sidecar")

_RUNNING_PROCESSES: dict[str, subprocess.Popen[str]] = {}
_RUNNING_PROCESSES_LOCK = threading.Lock()

WORKSPACE = Path(os.getenv("RDAGENT_WORKSPACE", "/tmp/rdagent_workspace"))
WORKSPACE.mkdir(parents=True, exist_ok=True)

_FACTOR_DATA_DIR = "git_ignore_folder/factor_implementation_source_data"
_FACTOR_DATA_DEBUG_DIR = "git_ignore_folder/factor_implementation_source_data_debug"
_OPENCODE_ZEN_API_BASE = "https://opencode.ai/zen/v1"
_OPENCODE_ZEN_CHAT_MODEL = "minimax-m2.5-free"
_OLLAMA_CHAT_MODEL = "ollama/qwen2.5:0.5b"
_OLLAMA_EMBEDDING_MODEL = "ollama/nomic-embed-text:latest"
_TIMEOUT_PER_ITERATION_SECONDS = int(os.getenv("RDAGENT_TIMEOUT_PER_ITERATION_SECONDS", "1800"))
_IDLE_TIMEOUT_SECONDS = int(os.getenv("RDAGENT_IDLE_TIMEOUT_SECONDS", "300"))
_SEEDED_FACTOR_COLUMNS = {
    "$open": [10.0, 11.2, 10.8, 11.5],
    "$high": [10.4, 11.5, 11.1, 11.8],
    "$low": [9.8, 10.9, 10.6, 11.1],
    "$close": [10.2, 11.3, 10.9, 11.7],
    "$volume": [1_000_000, 1_050_000, 980_000, 1_120_000],
    "$vwap": [10.1, 11.25, 10.85, 11.6],
}
_SEEDED_FACTOR_README = """# Seeded Factor Data

These lightweight HDF5 samples are generated by the QuantMate RD-Agent sidecar.
They provide a stable prompt-time schema for factor code generation without
triggering RD-Agent's heavyweight Qlib data bootstrap.
"""
_HDF_READ_FALLBACK_SITE_CUSTOMIZE = """
from pathlib import Path

import pandas as pd


_ORIGINAL_READ_HDF = pd.read_hdf


def _quantmate_read_hdf(path_or_buf, key=None, *args, **kwargs):
    if key is not None:
        return _ORIGINAL_READ_HDF(path_or_buf, key=key, *args, **kwargs)

    try:
        return _ORIGINAL_READ_HDF(path_or_buf, *args, **kwargs)
    except ValueError as exc:
        path_name = getattr(path_or_buf, "name", path_or_buf)
        base_name = Path(str(path_name)).name
        if base_name != "daily_pv.h5" or "multiple datasets" not in str(exc):
            raise

        for fallback_key in ("data", "df"):
            try:
                return _ORIGINAL_READ_HDF(path_or_buf, key=fallback_key, *args, **kwargs)
            except (KeyError, ValueError):
                continue
        raise


pd.read_hdf = _quantmate_read_hdf
""".lstrip()
_FACTOR_IMPLEMENTATION_GUIDANCE = """

Implementation requirements for generated factor code:
- Use pandas only for HDF5 IO. Do not import or use h5py.
- Read the input data with pd.read_hdf('daily_pv.h5', key='data').
- Write the final factor dataframe with DataFrame.to_hdf('result.h5', key='data', mode='w').
- The output must be a pandas DataFrame indexed by a MultiIndex named ('datetime', 'instrument').
- The output must contain exactly one factor column whose name matches the factor_name.
- For volume_ratio_20d, compute current day's volume divided by the 20-day rolling mean of volume,
  including the current row in the rolling window.
"""
_SENSITIVE_ERROR_PATTERNS = (
    re.compile(r"(?i)(authorization['\"]?\s*[:=]\s*['\"]?bearer\s+)([^'\"\s,]+)"),
    re.compile(r"(?i)((?:openai|opencode|litellm)[a-z0-9_]*api[_-]?key['\"]?\s*[:=]\s*['\"]?)([^'\"\s,]+)"),
    re.compile(r"(?i)\bsk-[A-Za-z0-9_-]{8,}\b"),
)
_RATE_LIMIT_ERROR_PATTERN = re.compile(r"(?i)(rate limit|too many requests|\b429\b)")
_RETRYABLE_PROVIDER_ERROR_PATTERN = re.compile(
    r"(?i)(rate limit|too many requests|\b429\b|timeout|timed out|deadline exceeded|connection reset|connection aborted|server disconnected|temporarily unavailable|stalled waiting for activity)"
)


def _build_rdagent_command(scenario: str, max_iterations: int) -> list[str]:
    command = {
        "fin_factor": "fin_factor",
        "fin_model": "fin_model",
        "fin_quant": "fin_quant",
    }.get(scenario, "fin_factor")
    return ["rdagent", command, "--step-n", str(max_iterations)]


def _redact_sensitive_error_text(error_text: str | None) -> str | None:
    if error_text is None:
        return None

    sanitized = str(error_text)
    for pattern in _SENSITIVE_ERROR_PATTERNS[:2]:
        sanitized = pattern.sub(r"\1[REDACTED]", sanitized)
    sanitized = _SENSITIVE_ERROR_PATTERNS[2].sub("sk-[REDACTED]", sanitized)
    return sanitized


def _summarize_process_error(stderr: str | None, *, limit: int = 1000) -> str | None:
    sanitized = _redact_sensitive_error_text(stderr)
    if not sanitized:
        return None

    lines = [line.strip() for line in sanitized.splitlines() if line.strip()]
    if not lines:
        return None

    interesting = [
        line
        for line in lines
        if re.search(
            r"(?i)(error|exception|traceback|failed|invalid|unauthor|forbidden|rate limit|timeout|429|5\d\d|4\d\d)",
            line,
        )
    ]
    selected = interesting[-8:] if interesting else lines[-8:]
    return "\n".join(selected)[:limit]


def _resolve_relative_run_path(run_dir: Path, configured_path: str) -> Path:
    path = Path(configured_path)
    return path if path.is_absolute() else run_dir / path


def _build_seed_factor_frame(debug: bool) -> pd.DataFrame:
    dates = pd.to_datetime(["2024-01-02", "2024-01-03"])
    instruments = ["SH600000"] if debug else ["SH600000", "SZ000001"]
    index = pd.MultiIndex.from_product(
        [dates, instruments],
        names=["datetime", "instrument"],
    )

    row_count = len(index)
    data = {
        column: values[:row_count]
        for column, values in _SEEDED_FACTOR_COLUMNS.items()
    }
    return pd.DataFrame(data, index=index)


def _build_prompt_context(prompt_context: str) -> str:
    base = prompt_context.rstrip()
    guidance = _FACTOR_IMPLEMENTATION_GUIDANCE.strip()
    return f"{base}\n\n{guidance}\n" if base else f"{guidance}\n"


def _build_seeded_factor_readme() -> str:
    return f"{_SEEDED_FACTOR_README.rstrip()}\n\n{_FACTOR_IMPLEMENTATION_GUIDANCE.strip()}\n"


def _build_sitecustomize_content() -> str:
    return _HDF_READ_FALLBACK_SITE_CUSTOMIZE


def _sitecustomize_support_dir(run_dir: Path) -> Path:
    return run_dir.parent / ".quantmate_support"


def _normalize_openai_compatible_model(model: str) -> str:
    normalized = model.strip()
    if not normalized or "/" in normalized:
        return normalized
    return f"openai/{normalized}"


def _is_rate_limit_error(error_text: str | None) -> bool:
    return bool(error_text and _RATE_LIMIT_ERROR_PATTERN.search(error_text))


def _is_retryable_provider_error(error_text: str | None) -> bool:
    return bool(error_text and _RETRYABLE_PROVIDER_ERROR_PATTERN.search(error_text))


def _workspace_rate_limit_error_text(run_dir: Path) -> str | None:
    for candidate in (run_dir / "selector.log", run_dir / "stderr.log"):
        if not candidate.exists() or not candidate.is_file():
            continue
        try:
            text = candidate.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        summary = _summarize_process_error(text, limit=2000)
        if _is_rate_limit_error(summary):
            return summary
        if _is_rate_limit_error(text):
            return _redact_sensitive_error_text(text[-2000:])
    return None


def _workspace_retryable_error_text(run_dir: Path) -> str | None:
    for candidate in (run_dir / "selector.log", run_dir / "stderr.log"):
        if not candidate.exists() or not candidate.is_file():
            continue
        try:
            text = candidate.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        summary = _summarize_process_error(text, limit=2000)
        if _is_retryable_provider_error(summary):
            return summary
        if _is_retryable_provider_error(text):
            return _redact_sensitive_error_text(text[-2000:])
    return None


def _workspace_activity_marker(run_dir: Path) -> tuple[int, int]:
    latest_mtime_ns = 0
    latest_size = 0
    for candidate in run_dir.rglob("*"):
        if not candidate.is_file():
            continue
        try:
            stat = candidate.stat()
        except OSError:
            continue
        marker = (stat.st_mtime_ns, stat.st_size)
        if marker > (latest_mtime_ns, latest_size):
            latest_mtime_ns, latest_size = marker
    return latest_mtime_ns, latest_size


def _seed_factor_prompt_data(run_dir: Path, env: dict[str, str]) -> None:
    targets = (
        (_resolve_relative_run_path(run_dir, env["FACTOR_CoSTEER_data_folder"]), _build_seed_factor_frame(False)),
        (
            _resolve_relative_run_path(run_dir, env["FACTOR_CoSTEER_data_folder_debug"]),
            _build_seed_factor_frame(True),
        ),
    )

    for target_dir, frame in targets:
        target_dir.mkdir(parents=True, exist_ok=True)

        data_path = target_dir / "daily_pv.h5"
        if not data_path.exists():
            frame.to_hdf(data_path, key="data", mode="w")
            frame.to_hdf(data_path, key="df", mode="a")

        readme_path = target_dir / "README.md"
        if not readme_path.exists():
            readme_path.write_text(_build_seeded_factor_readme(), encoding="utf-8")

    sitecustomize_path = run_dir / "sitecustomize.py"
    if not sitecustomize_path.exists():
        sitecustomize_path.write_text(_build_sitecustomize_content(), encoding="utf-8")

    support_dir = _sitecustomize_support_dir(run_dir)
    support_dir.mkdir(parents=True, exist_ok=True)
    support_sitecustomize_path = support_dir / "sitecustomize.py"
    if not support_sitecustomize_path.exists():
        support_sitecustomize_path.write_text(_build_sitecustomize_content(), encoding="utf-8")


def _register_running_process(run_id: str, process: subprocess.Popen[str]) -> None:
    with _RUNNING_PROCESSES_LOCK:
        _RUNNING_PROCESSES[run_id] = process


def _get_running_process(run_id: str) -> subprocess.Popen[str] | None:
    with _RUNNING_PROCESSES_LOCK:
        return _RUNNING_PROCESSES.get(run_id)


def _pop_running_process(run_id: str) -> subprocess.Popen[str] | None:
    with _RUNNING_PROCESSES_LOCK:
        return _RUNNING_PROCESSES.pop(run_id, None)


def _terminate_process(process: subprocess.Popen[str]) -> None:
    if process.poll() is not None:
        return

    try:
        os.killpg(process.pid, signal.SIGTERM)
    except ProcessLookupError:
        return

    try:
        process.wait(timeout=5)
        return
    except subprocess.TimeoutExpired:
        pass

    try:
        os.killpg(process.pid, signal.SIGKILL)
    except ProcessLookupError:
        return

    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        logger.warning("Timed out waiting for RD-Agent subprocess %s to exit", process.pid)


def _resolve_chat_model(env: dict[str, str], requested_model: str) -> str:
    model = requested_model.strip() if requested_model else ""
    if model.startswith("ollama/"):
        return model

    if env.get("OPENAI_API_KEY") and env.get("OPENAI_API_BASE") == env.get(
        "OPENCODE_AI_API_BASE", _OPENCODE_ZEN_API_BASE
    ):
        selected = model or env.get("RDAGENT_OPENCODE_CHAT_MODEL", _OPENCODE_ZEN_CHAT_MODEL)
        return _normalize_openai_compatible_model(selected)

    if env.get("OPENAI_API_KEY"):
        return model or env.get("CHAT_MODEL", "gpt-4o-mini")

    if env.get("OLLAMA_API_BASE"):
        return env.get("RDAGENT_OLLAMA_CHAT_MODEL", _OLLAMA_CHAT_MODEL)

    return model or env.get("CHAT_MODEL", "gpt-4o-mini")


def _build_rdagent_env(run_dir: Path, llm_model: str) -> dict[str, str]:
    env = os.environ.copy()
    explicit_ollama = (llm_model or "").strip().startswith("ollama/")
    for key in (
        "OPENAI_API_KEY",
        "OPENAI_API_BASE",
        "OPENAI_BASE_URL",
        "OPENCODE_AI_API_KEY",
        "OPENCODE_AI_API_BASE",
        "LITELLM_OPENAI_API_KEY",
        "LITELLM_CHAT_OPENAI_API_KEY",
        "LITELLM_CHAT_OPENAI_BASE_URL",
        "LITELLM_EMBEDDING_OPENAI_API_KEY",
        "LITELLM_EMBEDDING_OPENAI_BASE_URL",
    ):
        if env.get(key) == "":
            env.pop(key, None)

    if explicit_ollama:
        for key in (
            "OPENAI_API_KEY",
            "OPENAI_API_BASE",
            "OPENAI_BASE_URL",
            "OPENCODE_AI_API_KEY",
            "OPENCODE_AI_API_BASE",
            "LITELLM_OPENAI_API_KEY",
            "LITELLM_CHAT_OPENAI_API_KEY",
            "LITELLM_CHAT_OPENAI_BASE_URL",
            "LITELLM_EMBEDDING_OPENAI_API_KEY",
            "LITELLM_EMBEDDING_OPENAI_BASE_URL",
        ):
            env.pop(key, None)

    env["RDAGENT_WORKSPACE"] = str(run_dir)
    support_dir = _sitecustomize_support_dir(run_dir)
    existing_pythonpath = env.get("PYTHONPATH", "")
    injected_pythonpath = f"{support_dir}{os.pathsep}{run_dir}"
    env["PYTHONPATH"] = (
        injected_pythonpath if not existing_pythonpath else f"{injected_pythonpath}{os.pathsep}{existing_pythonpath}"
    )
    env["CONDA_DEFAULT_ENV"] = env.get("CONDA_DEFAULT_ENV") or "base"
    env["BACKEND"] = env.get("BACKEND") or "rdagent.oai.backend.LiteLLMAPIBackend"
    env["FACTOR_CoSTEER_python_bin"] = env.get("FACTOR_CoSTEER_python_bin") or sys.executable
    env["FACTOR_CoSTEER_data_folder"] = env.get("FACTOR_CoSTEER_data_folder") or _FACTOR_DATA_DIR
    env["FACTOR_CoSTEER_data_folder_debug"] = (
        env.get("FACTOR_CoSTEER_data_folder_debug") or _FACTOR_DATA_DEBUG_DIR
    )

    if not env.get("OPENAI_API_KEY") and env.get("OPENCODE_AI_API_KEY"):
        env["OPENAI_API_KEY"] = env["OPENCODE_AI_API_KEY"]
        env["OPENAI_API_BASE"] = env.get("OPENCODE_AI_API_BASE") or _OPENCODE_ZEN_API_BASE
        env["OPENAI_BASE_URL"] = env["OPENAI_API_BASE"]

    openai_api_key = env.get("OPENAI_API_KEY")
    openai_api_base = env.get("OPENAI_API_BASE") or env.get("OPENAI_BASE_URL")
    if openai_api_key:
        env["LITELLM_OPENAI_API_KEY"] = env.get("LITELLM_OPENAI_API_KEY") or openai_api_key
        env["LITELLM_CHAT_OPENAI_API_KEY"] = env.get("LITELLM_CHAT_OPENAI_API_KEY") or openai_api_key
        env["LITELLM_EMBEDDING_OPENAI_API_KEY"] = env.get("LITELLM_EMBEDDING_OPENAI_API_KEY") or openai_api_key
    if openai_api_base:
        env["OPENAI_API_BASE"] = openai_api_base
        env["OPENAI_BASE_URL"] = openai_api_base
        env["LITELLM_CHAT_OPENAI_BASE_URL"] = env.get("LITELLM_CHAT_OPENAI_BASE_URL") or openai_api_base
        env["LITELLM_EMBEDDING_OPENAI_BASE_URL"] = (
            env.get("LITELLM_EMBEDDING_OPENAI_BASE_URL") or openai_api_base
        )

    if env.get("OLLAMA_API_BASE"):
        env["EMBEDDING_MODEL"] = env.get("EMBEDDING_MODEL") or env.get(
            "RDAGENT_OLLAMA_EMBEDDING_MODEL", _OLLAMA_EMBEDDING_MODEL
        )
        if env["EMBEDDING_MODEL"].startswith("ollama/"):
            env["LITELLM_EMBEDDING_OPENAI_BASE_URL"] = env["OLLAMA_API_BASE"]
            env.pop("LITELLM_EMBEDDING_OPENAI_API_KEY", None)

    if explicit_ollama or (not env.get("OPENAI_API_KEY") and env.get("OLLAMA_API_BASE")):
        env["LITELLM_CHAT_STREAM"] = env.get("LITELLM_CHAT_STREAM") or "false"
        env["LITELLM_ENABLE_RESPONSE_SCHEMA"] = env.get("LITELLM_ENABLE_RESPONSE_SCHEMA") or "false"

    env["CHAT_MODEL"] = _resolve_chat_model(env, llm_model)
    return env


def _run_rdagent_process(
    run_id: str,
    run_dir: Path,
    scenario: str,
    max_iterations: int,
    env: dict[str, str],
) -> tuple[int, str | None]:
    process = subprocess.Popen(
        _build_rdagent_command(scenario, max_iterations),
        cwd=str(run_dir),
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        start_new_session=True,
    )
    _register_running_process(run_id, process)

    deadline = time.monotonic() + (max_iterations * _TIMEOUT_PER_ITERATION_SECONDS)
    last_activity_at = time.monotonic()
    last_activity_marker = _workspace_activity_marker(run_dir)
    stderr = None

    while True:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise subprocess.TimeoutExpired(process.args, max_iterations * _TIMEOUT_PER_ITERATION_SECONDS)

        try:
            _, stderr = process.communicate(timeout=min(5, remaining))
            break
        except subprocess.TimeoutExpired:
            current_marker = _workspace_activity_marker(run_dir)
            if current_marker != last_activity_marker:
                last_activity_marker = current_marker
                last_activity_at = time.monotonic()
                continue

            if _IDLE_TIMEOUT_SECONDS > 0 and time.monotonic() - last_activity_at >= _IDLE_TIMEOUT_SECONDS:
                logger.error(
                    "rdagent run %s stalled for %ds without workspace activity",
                    run_id,
                    _IDLE_TIMEOUT_SECONDS,
                )
                _terminate_process(process)
                try:
                    _, stderr = process.communicate(timeout=5)
                except subprocess.TimeoutExpired:
                    stderr = None
                error_summary = _summarize_process_error(stderr) or (
                    f"RD-Agent process stalled waiting for activity for {_IDLE_TIMEOUT_SECONDS} seconds"
                )
                return 124, error_summary

    logger.info("rdagent exited with code %d", process.returncode)
    error_summary = _summarize_process_error(stderr)
    if process.returncode != 0:
        logger.warning("rdagent stderr summary: %s", error_summary)

    return process.returncode, error_summary


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})


@app.route("/runs/<run_id>/cancel", methods=["POST"])
def cancel_run(run_id: str):
    process = _get_running_process(run_id)
    if process is None or process.poll() is not None:
        return jsonify({"run_id": run_id, "status": "not_running"})

    logger.info("Cancelling mining run %s", run_id)
    _terminate_process(process)
    return jsonify({"run_id": run_id, "status": "cancelled"})


@app.route("/mine", methods=["POST"])
def mine():
    """Execute an RD-Agent factor mining run.

    Expected JSON body:
    {
        "run_id": "uuid",
        "config": { "scenario": "fin_factor", "max_iterations": 10, ... },
        "prompt_context": "Available data fields..."
    }
    """
    data = request.get_json(force=True)
    run_id = data.get("run_id", "unknown")
    config = data.get("config", {})
    prompt_context = data.get("prompt_context", "")

    scenario = config.get("scenario", "fin_factor")
    max_iterations = config.get("max_iterations", 10)
    llm_model = config.get("llm_model", "gpt-4o-mini")

    logger.info("Starting mining run %s scenario=%s iters=%d", run_id, scenario, max_iterations)

    run_dir = WORKSPACE / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    (run_dir / "data_description.txt").write_text(_build_prompt_context(prompt_context), encoding="utf-8")

    try:
        env = _build_rdagent_env(run_dir, llm_model)
        _seed_factor_prompt_data(run_dir, env)
        returncode, error_summary = _run_rdagent_process(
            run_id,
            run_dir,
            scenario,
            max_iterations,
            env,
        )

        retryable_error = error_summary if _is_retryable_provider_error(error_summary) else _workspace_retryable_error_text(run_dir)

        ollama_model = env.get("RDAGENT_OLLAMA_CHAT_MODEL", _OLLAMA_CHAT_MODEL)
        if (
            returncode != 0
            and retryable_error
            and env.get("OLLAMA_API_BASE")
            and env.get("CHAT_MODEL") != ollama_model
        ):
            logger.warning(
                "rdagent run %s hit retryable provider failure on %s; retrying with ollama fallback %s",
                run_id,
                env.get("CHAT_MODEL"),
                ollama_model,
            )
            env = _build_rdagent_env(run_dir, ollama_model)
            _seed_factor_prompt_data(run_dir, env)
            returncode, error_summary = _run_rdagent_process(
                run_id,
                run_dir,
                scenario,
                max_iterations,
                env,
            )

        status = "cancelled" if returncode == -signal.SIGTERM else "completed" if returncode == 0 else "failed"

        return jsonify({
            "status": status,
            "iterations": _parse_iterations(run_dir, max_iterations),
            "discovered_factors": _parse_discovered_factors(run_dir),
            "error": error_summary if returncode != 0 else None,
        })

    except subprocess.TimeoutExpired:
        logger.error("Mining run %s timed out", run_id)
        process = _get_running_process(run_id)
        if process is not None:
            _terminate_process(process)
        return jsonify({"status": "failed", "error": "Mining run timed out", "iterations": [], "discovered_factors": []})
    except Exception as exc:
        logger.exception("Mining run %s failed: %s", run_id, exc)
        return jsonify({
            "status": "failed",
            "error": _redact_sensitive_error_text(str(exc)),
            "traceback": _redact_sensitive_error_text(traceback.format_exc()),
            "iterations": [],
            "discovered_factors": [],
        })
    finally:
        _pop_running_process(run_id)


def _parse_iterations(run_dir: Path, max_iters: int) -> list[dict]:
    """Parse RD-Agent iteration outputs from the workspace."""
    iterations = []
    for i in range(1, max_iters + 1):
        iter_dir = run_dir / f"iteration_{i}"
        if not iter_dir.exists():
            iter_dir = run_dir / f"round_{i}"
        if not iter_dir.exists():
            continue

        hypothesis_file = iter_dir / "hypothesis.txt"
        code_file = iter_dir / "factor.py"
        metrics_file = iter_dir / "metrics.json"
        feedback_file = iter_dir / "feedback.txt"

        iteration = {
            "iteration": i,
            "hypothesis": _read_text(hypothesis_file),
            "code": _read_text(code_file),
            "metrics": _read_json(metrics_file),
            "feedback": _read_text(feedback_file),
            "status": "completed",
        }
        iterations.append(iteration)

    if iterations:
        return iterations

    selector_log = _read_text(run_dir / "selector.log", limit=None)
    if not selector_log:
        return []

    discovered = _parse_selector_log_factors(selector_log)
    factor_files = _find_generated_factor_files(run_dir)
    if not discovered and not factor_files:
        return []

    generated_names = [factor["name"] for factor in discovered if factor.get("name")]
    if not generated_names:
        generated_names = [name for name in (_extract_factor_name_from_code(path) for path in factor_files) if name]

    hypothesis = None
    if generated_names:
        hypothesis = "Generated factors: " + ", ".join(generated_names)

    experiment_code = _read_text(factor_files[0]) if factor_files else None

    return [
        {
            "iteration": 1,
            "hypothesis": hypothesis,
            "code": experiment_code,
            "metrics": {
                "generated_factor_count": len(discovered) or len(factor_files),
            },
            "feedback": _extract_final_feedback(selector_log),
            "status": "completed",
        }
    ]


def _parse_discovered_factors(run_dir: Path) -> list[dict]:
    """Parse discovered factors from the final results."""
    factors: list[dict] = []
    results_file = run_dir / "results" / "factors.json"
    if not results_file.exists():
        results_file = run_dir / "final_factors.json"
    if results_file.exists():
        try:
            data = json.loads(results_file.read_text(encoding="utf-8"))
            factors = _normalize_discovered_factors(data)
        except (json.JSONDecodeError, OSError):
            pass

    if factors:
        return factors

    selector_log = _read_text(run_dir / "selector.log", limit=None)
    if not selector_log:
        return []

    return [_apply_default_factor_metrics(factor) for factor in _parse_selector_log_factors(selector_log)]


def _normalize_discovered_factors(payload: object) -> list[dict]:
    raw_factors: list[object] = []
    if isinstance(payload, list):
        raw_factors = payload
    elif isinstance(payload, dict):
        factors_value = payload.get("factors")
        if isinstance(factors_value, list):
            raw_factors = factors_value

    normalized: list[dict] = []
    for item in raw_factors:
        if not isinstance(item, dict):
            continue
        name = _pick_first_str(item, "name", "factor_name", "factor")
        if not name:
            continue
        normalized.append(
            _apply_default_factor_metrics(
                {
                    "name": name,
                    "expression": _pick_first_str(item, "expression", "factor_formulation", "formula") or name,
                    "description": _pick_first_str(item, "description", "factor_description"),
                    "ic_mean": _extract_metric_value(item, "ic_mean", "ic"),
                    "icir": _extract_metric_value(item, "icir", "ic_ir", "information_ratio"),
                    "sharpe": _extract_metric_value(item, "sharpe", "sharpe_ratio"),
                }
            )
        )

    return normalized


def _pick_first_str(data: dict, *keys: str) -> str | None:
    for key in keys:
        value = data.get(key)
        if isinstance(value, str):
            stripped = value.strip()
            if stripped:
                return stripped
    return None


def _extract_metric_value(data: object, *keys: str) -> float | None:
    if isinstance(data, dict):
        for key in keys:
            coerced = _coerce_metric(data.get(key))
            if coerced is not None:
                return coerced

        for nested_key in ("metrics", "metric", "stats", "statistics", "evaluation", "performance", "result"):
            nested = data.get(nested_key)
            coerced = _extract_metric_value(nested, *keys)
            if coerced is not None:
                return coerced

        for value in data.values():
            coerced = _extract_metric_value(value, *keys)
            if coerced is not None:
                return coerced

    elif isinstance(data, list):
        for item in data:
            coerced = _extract_metric_value(item, *keys)
            if coerced is not None:
                return coerced

    return None


def _coerce_metric(value: object) -> float | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            return None
        try:
            return float(stripped)
        except ValueError:
            return None
    return None


def _apply_default_factor_metrics(factor: dict) -> dict:
    normalized = dict(factor)
    for key in ("ic_mean", "icir", "sharpe"):
        normalized[key] = _coerce_metric(normalized.get(key))
        if normalized[key] is None:
            normalized[key] = 0.0
    return normalized


def _parse_selector_log_factors(log_text: str) -> list[dict]:
    factors: list[dict] = []
    block_matches = re.finditer(
        r"factor_name:\s*(?P<name>[^\n\\\"]+?)\s*(?:\\n|\n)"
        r"factor_description:\s*(?P<description>.+?)\s*(?:\\n|\n)"
        r"factor_formulation:\s*(?P<expression>.+?)(?:(?:\\n|\n)variables:|\")",
        log_text,
        re.DOTALL,
    )
    for match in block_matches:
        factors.append(
            {
                "name": match.group("name").strip(),
                "description": match.group("description").strip(),
                "expression": match.group("expression").strip(),
            }
        )

    current: dict[str, str] | None = None

    for raw_line in log_text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        if line.startswith("factor_name:"):
            if current and current.get("name"):
                factors.append(current)
            current = {"name": line.split(":", 1)[1].strip()}
            continue

        if current is None:
            continue

        if line.startswith("factor_description:"):
            current["description"] = line.split(":", 1)[1].strip()
        elif line.startswith("factor_formulation:"):
            current["expression"] = line.split(":", 1)[1].strip()

    if current and current.get("name"):
        factors.append(current)

    deduped: dict[str, dict] = {}
    for factor in factors:
        name = factor.get("name")
        if not name:
            continue
        deduped[name] = {
            "name": name,
            "expression": factor.get("expression") or name,
            "description": factor.get("description"),
        }

    return [_apply_default_factor_metrics(factor) for factor in deduped.values()]


def _extract_final_feedback(log_text: str) -> str | None:
    matches = re.findall(r'"final_feedback"\s*:\s*"((?:[^"\\]|\\.)*)"', log_text)
    if not matches:
        return None

    try:
        return json.loads(f'"{matches[-1]}"')[:10000]
    except json.JSONDecodeError:
        return matches[-1][:10000]


def _find_generated_factor_files(run_dir: Path) -> list[Path]:
    workspace_dir = run_dir / "git_ignore_folder" / "RD-Agent_workspace"
    if not workspace_dir.exists():
        return []
    return sorted(workspace_dir.glob("*/factor.py"))


def _extract_factor_name_from_code(path: Path) -> str | None:
    code = _read_text(path)
    if not code:
        return None
    match = re.search(r"def\s+calculate_([A-Za-z0-9_]+)\s*\(", code)
    if match:
        return match.group(1)
    return None


def _read_text(path: Path, limit: int | None = 10000) -> str | None:
    if path.exists():
        try:
            content = path.read_text(encoding="utf-8")
            if limit is None:
                return content
            return content[:limit]
        except OSError:
            return None
    return None


def _read_json(path: Path) -> dict | None:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return None
    return None


def main() -> None:
    port = int(os.getenv("RDAGENT_SERVICE_PORT", os.getenv("PORT", "8001")))
    app.run(host="0.0.0.0", port=port)