from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal

SystemConfigValueType = Literal["string", "int", "float", "bool", "csv"]


@dataclass(frozen=True)
class SystemConfigDefinition:
    key: str
    category: str
    label: str
    description: str
    value_type: SystemConfigValueType
    default_value: str
    legacy_env_keys: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


def _cfg(
    key: str,
    *,
    category: str,
    label: str,
    description: str,
    value_type: SystemConfigValueType,
    default_value: str,
    legacy_env_keys: str | tuple[str, ...] = (),
) -> SystemConfigDefinition:
    if isinstance(legacy_env_keys, str):
        normalized_env_keys = (legacy_env_keys,) if legacy_env_keys else ()
    else:
        normalized_env_keys = tuple(item for item in legacy_env_keys if item)
    return SystemConfigDefinition(
        key=key,
        category=category,
        label=label,
        description=description,
        value_type=value_type,
        default_value=default_value,
        legacy_env_keys=normalized_env_keys,
    )


DB_SYSTEM_CONFIG_DEFINITIONS: tuple[SystemConfigDefinition, ...] = (
    _cfg(
        "datasync.sync_hour",
        category="datasync",
        label="Daily sync hour",
        description="Daily sync schedule hour in 24-hour local time.",
        value_type="int",
        default_value="2",
        legacy_env_keys="SYNC_HOUR",
    ),
    _cfg(
        "datasync.sync_minute",
        category="datasync",
        label="Daily sync minute",
        description="Daily sync schedule minute in local time.",
        value_type="int",
        default_value="0",
        legacy_env_keys="SYNC_MINUTE",
    ),
    _cfg(
        "datasync.timezone",
        category="datasync",
        label="Data sync timezone",
        description="Timezone used by scheduler windows and sync dashboards.",
        value_type="string",
        default_value="Asia/Shanghai",
        legacy_env_keys="DATASYNC_TIMEZONE",
    ),
    _cfg(
        "datasync.batch_size",
        category="datasync",
        label="Sync batch size",
        description="Default batch size for interface-level sync fetches.",
        value_type="int",
        default_value="100",
        legacy_env_keys="BATCH_SIZE",
    ),
    _cfg(
        "datasync.max_retries",
        category="datasync",
        label="Sync max retries",
        description="Maximum retry count for sync engine retries.",
        value_type="int",
        default_value="3",
        legacy_env_keys="MAX_RETRIES",
    ),
    _cfg(
        "datasync.sync_parallel_workers",
        category="datasync",
        label="Daily sync workers",
        description="Worker count for regular daily sync dispatch.",
        value_type="int",
        default_value="4",
        legacy_env_keys="SYNC_PARALLEL_WORKERS",
    ),
    _cfg(
        "datasync.backfill_workers",
        category="datasync",
        label="Backfill workers",
        description="Worker count for backfill retry execution.",
        value_type="int",
        default_value="10",
        legacy_env_keys="BACKFILL_WORKERS",
    ),
    _cfg(
        "datasync.backfill_idle_interval_hours",
        category="datasync",
        label="Backfill idle interval",
        description="Sleep hours between empty backfill loop passes.",
        value_type="int",
        default_value="4",
        legacy_env_keys="BACKFILL_IDLE_INTERVAL_HOURS",
    ),
    _cfg(
        "datasync.backfill_lock_retry_seconds",
        category="datasync",
        label="Backfill lock retry seconds",
        description="Retry interval when another backfill worker owns the DB lock.",
        value_type="int",
        default_value="60",
        legacy_env_keys="BACKFILL_LOCK_RETRY_SECONDS",
    ),
    _cfg(
        "datasync.backfill_lock_stale_hours",
        category="datasync",
        label="Backfill lock stale hours",
        description="Running status stale threshold for backfill lock recovery.",
        value_type="int",
        default_value="6",
        legacy_env_keys="BACKFILL_LOCK_STALE_HOURS",
    ),
    _cfg(
        "datasync.sync_status_running_stale_hours",
        category="datasync",
        label="Running status stale hours",
        description="Threshold used to reopen stuck running sync records.",
        value_type="int",
        default_value="6",
        legacy_env_keys="SYNC_STATUS_RUNNING_STALE_HOURS",
    ),
    _cfg(
        "datasync.sync_init.batch_size",
        category="datasync",
        label="Sync status init batch size",
        description="Trade-date batch size used when filling missing sync status rows.",
        value_type="int",
        default_value="500",
        legacy_env_keys="SYNC_INIT_BATCH_SIZE",
    ),
    _cfg(
        "datasync.dashboard.cache_ttl_seconds",
        category="datasync",
        label="Dashboard cache TTL",
        description="Seconds to cache sync dashboard snapshots.",
        value_type="int",
        default_value="30",
        legacy_env_keys="DATASYNC_DASHBOARD_CACHE_TTL_SECONDS",
    ),
    _cfg(
        "datasync.backfill_job_timeout_seconds",
        category="datasync",
        label="Backfill job timeout",
        description="RQ timeout for queued backfill jobs.",
        value_type="int",
        default_value="3600",
        legacy_env_keys="DATASYNC_BACKFILL_JOB_TIMEOUT_SECONDS",
    ),
    _cfg(
        "api.manual_datasync_job_timeout_seconds",
        category="datasync",
        label="Manual sync job timeout",
        description="RQ timeout for manually triggered daily sync jobs.",
        value_type="int",
        default_value="1800",
        legacy_env_keys="MANUAL_DATASYNC_JOB_TIMEOUT_SECONDS",
    ),
    _cfg(
        "datasync.akshare.calls_per_min.default",
        category="datasync",
        label="AkShare default calls per minute",
        description="Default rate limit for AkShare sync APIs without endpoint-specific overrides.",
        value_type="int",
        default_value="30",
        legacy_env_keys="AKSHARE_CALLS_PER_MIN",
    ),
    _cfg(
        "datasync.akshare.max_retries",
        category="datasync",
        label="AkShare max retries",
        description="Maximum retry count for AkShare fetch failures.",
        value_type="int",
        default_value="3",
        legacy_env_keys="AKSHARE_MAX_RETRIES",
    ),
    _cfg(
        "datasync.akshare.backoff_base_seconds",
        category="datasync",
        label="AkShare backoff base seconds",
        description="Base backoff interval used after AkShare throttling or transient failures.",
        value_type="int",
        default_value="5",
        legacy_env_keys="AKSHARE_BACKOFF_BASE_SECONDS",
    ),
    _cfg(
        "datasync.source_concurrency.tushare",
        category="datasync",
        label="Tushare daily concurrency",
        description="Maximum concurrent Tushare daily sync calls.",
        value_type="int",
        default_value="3",
        legacy_env_keys="TUSHARE_CONCURRENCY",
    ),
    _cfg(
        "datasync.backfill_source_concurrency.tushare",
        category="datasync",
        label="Tushare backfill concurrency",
        description="Maximum concurrent Tushare backfill calls.",
        value_type="int",
        default_value="3",
        legacy_env_keys="BACKFILL_TUSHARE_CONCURRENCY",
    ),
    _cfg(
        "datasync.tushare.token_points",
        category="datasync",
        label="Tushare token points",
        description="Capability hint used to decide which registry-backed Tushare APIs are sync-supported.",
        value_type="int",
        default_value="0",
        legacy_env_keys="TUSHARE_TOKEN_POINTS",
    ),
    _cfg(
        "datasync.tushare.granted_api_names",
        category="datasync",
        label="Tushare granted API names",
        description="Comma-separated list of token-granted Tushare API names.",
        value_type="csv",
        default_value="",
        legacy_env_keys="TUSHARE_GRANTED_API_NAMES",
    ),
    _cfg(
        "backtest.default_capital",
        category="backtest",
        label="Backtest default capital",
        description="Default capital used by single backtest forms and tasks.",
        value_type="float",
        default_value="100000.0",
        legacy_env_keys="BACKTEST_DEFAULT_CAPITAL",
    ),
    _cfg(
        "backtest.default_rate",
        category="backtest",
        label="Backtest default commission rate",
        description="Default commission rate used by backtests.",
        value_type="float",
        default_value="0.0001",
        legacy_env_keys="BACKTEST_DEFAULT_RATE",
    ),
    _cfg(
        "backtest.default_slippage",
        category="backtest",
        label="Backtest default slippage",
        description="Default slippage applied in backtests.",
        value_type="float",
        default_value="0.0",
        legacy_env_keys="BACKTEST_DEFAULT_SLIPPAGE",
    ),
    _cfg(
        "backtest.default_size",
        category="backtest",
        label="Backtest default contract size",
        description="Default lot size used by backtests.",
        value_type="int",
        default_value="1",
        legacy_env_keys="BACKTEST_DEFAULT_SIZE",
    ),
    _cfg(
        "backtest.default_pricetick",
        category="backtest",
        label="Backtest default price tick",
        description="Default price tick used by backtests.",
        value_type="float",
        default_value="0.01",
        legacy_env_keys="BACKTEST_DEFAULT_PRICETICK",
    ),
    _cfg(
        "backtest.default_benchmark",
        category="backtest",
        label="Backtest default benchmark",
        description="Default benchmark symbol used by backtests and optimizations.",
        value_type="string",
        default_value="399300.SZ",
        legacy_env_keys="BACKTEST_DEFAULT_BENCHMARK",
    ),
    _cfg(
        "backtest.job_timeout_seconds",
        category="backtest",
        label="Backtest job timeout",
        description="RQ timeout for single backtest jobs.",
        value_type="int",
        default_value="3600",
        legacy_env_keys="BACKTEST_JOB_TIMEOUT_SECONDS",
    ),
    _cfg(
        "backtest.bulk_job_timeout_seconds",
        category="backtest",
        label="Bulk backtest job timeout",
        description="RQ timeout for bulk backtest jobs.",
        value_type="int",
        default_value="7200",
        legacy_env_keys="BACKTEST_BULK_JOB_TIMEOUT_SECONDS",
    ),
    _cfg(
        "backtest.optimization_job_timeout_seconds",
        category="backtest",
        label="Optimization job timeout",
        description="RQ timeout for optimization jobs dispatched from backtest flows.",
        value_type="int",
        default_value="14400",
        legacy_env_keys="BACKTEST_OPTIMIZATION_JOB_TIMEOUT_SECONDS",
    ),
    _cfg(
        "backtest.result_ttl_seconds",
        category="backtest",
        label="Backtest result TTL",
        description="Seconds to keep stored backtest results and artifacts.",
        value_type="int",
        default_value="604800",
        legacy_env_keys="BACKTEST_RESULT_TTL_SECONDS",
    ),
    _cfg(
        "backtest.optimization.task_job_timeout_seconds",
        category="backtest",
        label="Optimization task timeout",
        description="RQ timeout for optimization task jobs.",
        value_type="int",
        default_value="14400",
        legacy_env_keys="OPTIMIZATION_TASK_JOB_TIMEOUT_SECONDS",
    ),
    _cfg(
        "backtest.optimization.task_result_ttl_seconds",
        category="backtest",
        label="Optimization result TTL",
        description="Seconds to keep optimization task results.",
        value_type="int",
        default_value="259200",
        legacy_env_keys="OPTIMIZATION_TASK_RESULT_TTL_SECONDS",
    ),
    _cfg(
        "backtest.optimization.max_workers",
        category="backtest",
        label="Optimization max workers",
        description="Maximum worker count used by optimization tasks.",
        value_type="int",
        default_value="4",
        legacy_env_keys="OPTIMIZATION_MAX_WORKERS",
    ),
    _cfg(
        "backtest.optimization.default_rate",
        category="backtest",
        label="Optimization default rate",
        description="Default commission rate used by optimization tasks.",
        value_type="float",
        default_value="0.0003",
        legacy_env_keys="OPTIMIZATION_DEFAULT_RATE",
    ),
    _cfg(
        "backtest.optimization.default_slippage",
        category="backtest",
        label="Optimization default slippage",
        description="Default slippage used by optimization tasks.",
        value_type="float",
        default_value="0.0001",
        legacy_env_keys="OPTIMIZATION_DEFAULT_SLIPPAGE",
    ),
    _cfg(
        "trading.default_slippage",
        category="trading",
        label="Trading default slippage",
        description="Default live-trading slippage assumption for order matching.",
        value_type="float",
        default_value="0.001",
        legacy_env_keys="TRADING_DEFAULT_SLIPPAGE",
    ),
    _cfg(
        "market.calendar.trade_days_cache_ttl_seconds",
        category="market",
        label="Trade days cache TTL",
        description="Seconds to cache trade-day responses.",
        value_type="int",
        default_value="300",
        legacy_env_keys="MARKET_CALENDAR_TRADE_DAYS_CACHE_TTL_SECONDS",
    ),
    _cfg(
        "market.calendar.events_cache_ttl_seconds",
        category="market",
        label="Calendar events cache TTL",
        description="Seconds to cache market event responses.",
        value_type="int",
        default_value="300",
        legacy_env_keys="MARKET_CALENDAR_EVENTS_CACHE_TTL_SECONDS",
    ),
    _cfg(
        "market.calendar.max_events_per_type",
        category="market",
        label="Calendar max events per type",
        description="Maximum number of events returned for each event category.",
        value_type="int",
        default_value="30",
        legacy_env_keys="MARKET_CALENDAR_MAX_EVENTS_PER_TYPE",
    ),
    _cfg(
        "market.sentiment.cache_ttl_seconds",
        category="market",
        label="Sentiment cache TTL",
        description="Seconds to cache market sentiment snapshots.",
        value_type="int",
        default_value="60",
        legacy_env_keys="MARKET_SENTIMENT_CACHE_TTL_SECONDS",
    ),
    _cfg(
        "realtime_quote.bulk_cache_ttl_seconds",
        category="market",
        label="Realtime bulk cache TTL",
        description="Seconds to reuse cached bulk quote responses.",
        value_type="int",
        default_value="60",
        legacy_env_keys="REALTIME_QUOTE_BULK_CACHE_TTL_SECONDS",
    ),
    _cfg(
        "realtime_quote.akshare_timeout_seconds",
        category="market",
        label="Realtime AkShare timeout",
        description="Timeout in seconds for AkShare realtime quote requests.",
        value_type="float",
        default_value="15.0",
        legacy_env_keys="REALTIME_QUOTE_AKSHARE_TIMEOUT_SECONDS",
    ),
    _cfg(
        "realtime_quote.tencent_timeout_seconds",
        category="market",
        label="Tencent quote timeout",
        description="Timeout in seconds for Tencent quote requests.",
        value_type="float",
        default_value="8.0",
        legacy_env_keys="REALTIME_QUOTE_TENCENT_TIMEOUT_SECONDS",
    ),
    _cfg(
        "realtime_quote.tencent_retries",
        category="market",
        label="Tencent quote retries",
        description="Retry count for Tencent quote timeouts or connection errors.",
        value_type="int",
        default_value="2",
        legacy_env_keys="REALTIME_QUOTE_TENCENT_RETRIES",
    ),
    _cfg(
        "realtime_quote.tencent_backoff_seconds",
        category="market",
        label="Tencent quote backoff",
        description="Base backoff in seconds between Tencent quote retries.",
        value_type="float",
        default_value="1.0",
        legacy_env_keys="REALTIME_QUOTE_TENCENT_BACKOFF_SECONDS",
    ),
    _cfg(
        "worker.default_queue_names",
        category="worker",
        label="Default worker queues",
        description="Comma-separated queue names used when a worker starts without explicit queue arguments.",
        value_type="csv",
        default_value="backtest,optimization,default,low",
        legacy_env_keys="WORKER_DEFAULT_QUEUE_NAMES",
    ),
    _cfg(
        "worker.queue_timeout.high",
        category="worker",
        label="High queue timeout",
        description="Default RQ timeout for the high priority queue.",
        value_type="int",
        default_value="600",
        legacy_env_keys="QUEUE_HIGH_DEFAULT_TIMEOUT_SECONDS",
    ),
    _cfg(
        "worker.queue_timeout.default",
        category="worker",
        label="Default queue timeout",
        description="Default RQ timeout for the standard queue.",
        value_type="int",
        default_value="1800",
        legacy_env_keys="QUEUE_DEFAULT_DEFAULT_TIMEOUT_SECONDS",
    ),
    _cfg(
        "worker.queue_timeout.low",
        category="worker",
        label="Low queue timeout",
        description="Default RQ timeout for the low priority queue.",
        value_type="int",
        default_value="3600",
        legacy_env_keys="QUEUE_LOW_DEFAULT_TIMEOUT_SECONDS",
    ),
    _cfg(
        "worker.queue_timeout.backtest",
        category="worker",
        label="Backtest queue timeout",
        description="Default RQ timeout for the backtest queue.",
        value_type="int",
        default_value="3600",
        legacy_env_keys="QUEUE_BACKTEST_DEFAULT_TIMEOUT_SECONDS",
    ),
    _cfg(
        "worker.queue_timeout.optimization",
        category="worker",
        label="Optimization queue timeout",
        description="Default RQ timeout for the optimization queue.",
        value_type="int",
        default_value="7200",
        legacy_env_keys="QUEUE_OPTIMIZATION_DEFAULT_TIMEOUT_SECONDS",
    ),
    _cfg(
        "worker.queue_timeout.rdagent",
        category="worker",
        label="RD-Agent queue timeout",
        description="Default RQ timeout for the RD-Agent queue.",
        value_type="int",
        default_value="14400",
        legacy_env_keys="QUEUE_RDAGENT_DEFAULT_TIMEOUT_SECONDS",
    ),
    _cfg(
        "jobs.storage_ttl_seconds",
        category="jobs",
        label="Job storage TTL",
        description="Seconds to keep persisted job metadata in Redis.",
        value_type="int",
        default_value="604800",
        legacy_env_keys="JOB_STORAGE_TTL_SECONDS",
    ),
    _cfg(
        "rdagent.request_timeout_seconds",
        category="rdagent",
        label="RD-Agent request timeout",
        description="Timeout in seconds for RD-Agent sidecar HTTP requests.",
        value_type="float",
        default_value="14400.0",
        legacy_env_keys="RDAGENT_REQUEST_TIMEOUT_SECONDS",
    ),
    _cfg(
        "cli.redis_socket_timeout_seconds",
        category="jobs",
        label="CLI Redis socket timeout",
        description="Socket timeout in seconds for CLI Redis health checks.",
        value_type="float",
        default_value="2.0",
        legacy_env_keys="CLI_REDIS_SOCKET_TIMEOUT_SECONDS",
    ),
)

DB_SYSTEM_CONFIGS_BY_KEY: dict[str, SystemConfigDefinition] = {
    definition.key: definition for definition in DB_SYSTEM_CONFIG_DEFINITIONS
}

DB_SYSTEM_CONFIG_KEYS = frozenset(DB_SYSTEM_CONFIGS_BY_KEY)

ENV_ONLY_SYSTEM_CONFIG_KEYS = frozenset(
    {
        "app.environment",
        "api.host",
        "api.port",
        "app.build_time",
        "auth.admin_username",
        "auth.admin_email",
        "logging.format",
        "logging.level",
        "rdagent.sidecar_url",
        "datasync.dry_run",
        "datasync.legacy_backfill_lookback_days",
        "datasync.legacy_reconcile_lookback_years",
        "datasync.backfill_interval_hours",
    }
)


def get_db_system_config_definition(key: str) -> SystemConfigDefinition | None:
    return DB_SYSTEM_CONFIGS_BY_KEY.get(key)


def is_db_system_config_key(key: str | None) -> bool:
    return bool(key) and key in DB_SYSTEM_CONFIG_KEYS


def is_env_only_system_config_key(key: str | None) -> bool:
    return bool(key) and key in ENV_ONLY_SYSTEM_CONFIG_KEYS


def list_db_system_config_definitions() -> list[SystemConfigDefinition]:
    return list(DB_SYSTEM_CONFIG_DEFINITIONS)
