"""Bridge that turns selected factors into a deployable composite strategy.

Flow: selected factors → (weighted expression) → composite components →
composite strategy → guardrail review → PaperTradingService.deploy.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

from app.domains.autopilot.guardrails import pre_deploy_review, request_approval
from app.domains.autopilot.policies import Policies
from app.domains.composite.service import CompositeStrategyService
from app.domains.trading.paper_trading_service import PaperTradingService

logger = logging.getLogger(__name__)

_UNIVERSE_SUBTYPE = "index_constituents"
_TRADING_SUBTYPE = "multi_factor_alpha"
_RISK_SUBTYPE = "position_limits"


def _factor_expression(factor: Dict[str, Any]) -> str:
    expr = str(factor.get("expression") or factor.get("name") or "").strip()
    if not expr:
        raise ValueError("Factor requires an expression or name")
    return expr


def build_combined_expression(factors: List[Dict[str, Any]]) -> str:
    """Combine selected factors into a single weighted long-short expression."""
    terms: List[str] = []
    for f in factors:
        expr = _factor_expression(f)
        direction = float(f.get("direction", 1.0) or 1.0)
        weight = float(f.get("weight", 1.0) or 1.0)
        coeff = direction * weight
        terms.append(f"({coeff:.6f} * ({expr}))")
    if not terms:
        raise ValueError("No factors provided to build expression")
    return " + ".join(terms)


def build_composite_strategy(
    user_id: int,
    selected_factors: List[Dict[str, Any]],
    universe_symbols: List[str],
    policies: Policies,
) -> Dict[str, Any]:
    """Persist components + composite strategy and return the composite detail."""
    if not selected_factors:
        raise ValueError("No selected factors to deploy")
    if not universe_symbols:
        raise ValueError("Empty universe; cannot build composite strategy")

    expression = build_combined_expression(selected_factors)
    service = CompositeStrategyService()

    universe_component = service.create_component(
        user_id=user_id,
        name=f"AP Universe {_ts()}",
        layer="universe",
        sub_type=_UNIVERSE_SUBTYPE,
        description=None,
        code=None,
        config={
            "symbols": list(universe_symbols),
            "factor_expression": expression,
            "direction": 1.0,
            "top_n": min(100, len(universe_symbols)),
        },
        parameters={},
    )
    trading_component = service.create_component(
        user_id=user_id,
        name=f"AP Trading {_ts()}",
        layer="trading",
        sub_type=_TRADING_SUBTYPE,
        description=None,
        code=None,
        config={
            "factor_expression": expression,
            "direction": 1.0,
            "top_n": max(1, policies.top_n_factor),
            "close_on_universe_exit": True,
        },
        parameters={},
    )
    risk_component = service.create_component(
        user_id=user_id,
        name=f"AP Risk {_ts()}",
        layer="risk",
        sub_type=_RISK_SUBTYPE,
        description=None,
        code=None,
        config={
            "max_total_positions": max(1, policies.top_n_factor),
            "max_position_pct": policies.max_position_pct,
            "stop_loss_pct": 0.05,
        },
        parameters={},
    )

    bindings = [
        {"component_id": universe_component["id"], "layer": "universe", "ordinal": 0, "weight": 1.0},
        {"component_id": trading_component["id"], "layer": "trading", "ordinal": 1, "weight": 1.0},
        {"component_id": risk_component["id"], "layer": "risk", "ordinal": 2, "weight": 1.0},
    ]

    composite = service.create_composite(
        user_id=user_id,
        name=f"Autopilot Composite {_ts()}",
        description="Generated by autopilot research loop",
        portfolio_config={"initial_capital": 1_000_000.0},
        market_constraints={},
        execution_mode="auto",
        bindings=bindings,
    )
    composite["expression"] = expression
    return composite


def deploy(
    user_id: int,
    composite_strategy_id: int,
    paper_account_id: int,
    selected_factors: List[Dict[str, Any]],
    policies: Policies,
    *,
    source_backtest_job_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Review then deploy a composite strategy through PaperTradingService."""
    review = pre_deploy_review(
        {
            "factors": selected_factors,
            "min_overlap_days": policies.min_overlap_days,
        },
        policies,
    )
    if not review["ok"]:
        return {"success": False, "error": review["reason"], "risk_summary": review["risk_summary"]}

    approval = request_approval({"kinetic": False}, policies)
    if approval != "auto":
        # Requires manual approval: record intent instead of deploying.
        return {
            "success": False,
            "error": "Deployment requires manual approval",
            "approval_status": "pending_approval",
            "composite_strategy_id": composite_strategy_id,
        }

    service = PaperTradingService()
    return service.deploy(
        user_id=user_id,
        strategy_id=None,
        vt_symbol="",
        parameters={},
        paper_account_id=paper_account_id,
        execution_mode="auto",
        source_backtest_job_id=source_backtest_job_id,
        strategy_source_type="composite",
        composite_strategy_id=composite_strategy_id,
    )


def _ts() -> str:
    return datetime.utcnow().strftime("%Y%m%d%H%M%S%f")[:15]