"""RD-Agent Sidecar — thin Flask wrapper around rdagent CLI.

Accepts mining requests from QuantMate's RQ worker and executes the
RD-Agent R&D loop. Returns iteration results and discovered factors.
"""

from __future__ import annotations

import json
import logging
import os
import signal
import subprocess
import sys
import threading
import traceback
from pathlib import Path

import pandas as pd
from flask import Flask, jsonify, request

app = Flask(__name__)
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("rdagent-sidecar")

_RUNNING_PROCESSES: dict[str, subprocess.Popen[str]] = {}
_RUNNING_PROCESSES_LOCK = threading.Lock()

WORKSPACE = Path(os.getenv("RDAGENT_WORKSPACE", "/tmp/rdagent_workspace"))
WORKSPACE.mkdir(parents=True, exist_ok=True)

_FACTOR_DATA_DIR = "git_ignore_folder/factor_implementation_source_data"
_FACTOR_DATA_DEBUG_DIR = "git_ignore_folder/factor_implementation_source_data_debug"
_OPENCODE_ZEN_API_BASE = "https://opencode.ai/zen/v1"
_OPENCODE_ZEN_CHAT_MODEL = "minimax-m2.5-free"
_OLLAMA_CHAT_MODEL = "ollama/qwen2.5:0.5b"
_OLLAMA_EMBEDDING_MODEL = "ollama/nomic-embed-text:latest"
_TIMEOUT_PER_ITERATION_SECONDS = int(os.getenv("RDAGENT_TIMEOUT_PER_ITERATION_SECONDS", "1800"))
_SEEDED_FACTOR_COLUMNS = {
    "$open": [10.0, 11.2, 10.8, 11.5],
    "$high": [10.4, 11.5, 11.1, 11.8],
    "$low": [9.8, 10.9, 10.6, 11.1],
    "$close": [10.2, 11.3, 10.9, 11.7],
    "$volume": [1_000_000, 1_050_000, 980_000, 1_120_000],
    "$vwap": [10.1, 11.25, 10.85, 11.6],
}
_SEEDED_FACTOR_README = """# Seeded Factor Data

These lightweight HDF5 samples are generated by the QuantMate RD-Agent sidecar.
They provide a stable prompt-time schema for factor code generation without
triggering RD-Agent's heavyweight Qlib data bootstrap.
"""


def _build_rdagent_command(scenario: str, max_iterations: int) -> list[str]:
    command = {
        "fin_factor": "fin_factor",
        "fin_model": "fin_model",
        "fin_quant": "fin_quant",
    }.get(scenario, "fin_factor")
    return ["rdagent", command, "--step-n", str(max_iterations)]


def _resolve_relative_run_path(run_dir: Path, configured_path: str) -> Path:
    path = Path(configured_path)
    return path if path.is_absolute() else run_dir / path


def _build_seed_factor_frame(debug: bool) -> pd.DataFrame:
    dates = pd.to_datetime(["2024-01-02", "2024-01-03"])
    instruments = ["SH600000"] if debug else ["SH600000", "SZ000001"]
    index = pd.MultiIndex.from_product(
        [dates, instruments],
        names=["datetime", "instrument"],
    )

    row_count = len(index)
    data = {
        column: values[:row_count]
        for column, values in _SEEDED_FACTOR_COLUMNS.items()
    }
    return pd.DataFrame(data, index=index)


def _normalize_openai_compatible_model(model: str) -> str:
    normalized = model.strip()
    if not normalized or "/" in normalized:
        return normalized
    return f"openai/{normalized}"


def _seed_factor_prompt_data(run_dir: Path, env: dict[str, str]) -> None:
    targets = (
        (_resolve_relative_run_path(run_dir, env["FACTOR_CoSTEER_data_folder"]), _build_seed_factor_frame(False)),
        (
            _resolve_relative_run_path(run_dir, env["FACTOR_CoSTEER_data_folder_debug"]),
            _build_seed_factor_frame(True),
        ),
    )

    for target_dir, frame in targets:
        target_dir.mkdir(parents=True, exist_ok=True)

        data_path = target_dir / "daily_pv.h5"
        if not data_path.exists():
            frame.to_hdf(data_path, key="data", mode="w")

        readme_path = target_dir / "README.md"
        if not readme_path.exists():
            readme_path.write_text(_SEEDED_FACTOR_README, encoding="utf-8")


def _register_running_process(run_id: str, process: subprocess.Popen[str]) -> None:
    with _RUNNING_PROCESSES_LOCK:
        _RUNNING_PROCESSES[run_id] = process


def _get_running_process(run_id: str) -> subprocess.Popen[str] | None:
    with _RUNNING_PROCESSES_LOCK:
        return _RUNNING_PROCESSES.get(run_id)


def _pop_running_process(run_id: str) -> subprocess.Popen[str] | None:
    with _RUNNING_PROCESSES_LOCK:
        return _RUNNING_PROCESSES.pop(run_id, None)


def _terminate_process(process: subprocess.Popen[str]) -> None:
    if process.poll() is not None:
        return

    try:
        os.killpg(process.pid, signal.SIGTERM)
    except ProcessLookupError:
        return

    try:
        process.wait(timeout=5)
        return
    except subprocess.TimeoutExpired:
        pass

    try:
        os.killpg(process.pid, signal.SIGKILL)
    except ProcessLookupError:
        return

    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        logger.warning("Timed out waiting for RD-Agent subprocess %s to exit", process.pid)


def _resolve_chat_model(env: dict[str, str], requested_model: str) -> str:
    model = requested_model.strip() if requested_model else ""
    if model.startswith("ollama/"):
        return model

    if env.get("OPENAI_API_KEY") and env.get("OPENAI_API_BASE") == env.get(
        "OPENCODE_AI_API_BASE", _OPENCODE_ZEN_API_BASE
    ):
        selected = model or env.get("RDAGENT_OPENCODE_CHAT_MODEL", _OPENCODE_ZEN_CHAT_MODEL)
        return _normalize_openai_compatible_model(selected)

    if env.get("OPENAI_API_KEY"):
        return model or env.get("CHAT_MODEL", "gpt-4o-mini")

    if env.get("OLLAMA_API_BASE"):
        return env.get("RDAGENT_OLLAMA_CHAT_MODEL", _OLLAMA_CHAT_MODEL)

    return model or env.get("CHAT_MODEL", "gpt-4o-mini")


def _build_rdagent_env(run_dir: Path, llm_model: str) -> dict[str, str]:
    env = os.environ.copy()
    for key in (
        "OPENAI_API_KEY",
        "OPENAI_API_BASE",
        "OPENAI_BASE_URL",
        "OPENCODE_AI_API_KEY",
        "OPENCODE_AI_API_BASE",
        "LITELLM_OPENAI_API_KEY",
        "LITELLM_CHAT_OPENAI_API_KEY",
        "LITELLM_CHAT_OPENAI_BASE_URL",
        "LITELLM_EMBEDDING_OPENAI_API_KEY",
        "LITELLM_EMBEDDING_OPENAI_BASE_URL",
    ):
        if env.get(key) == "":
            env.pop(key, None)

    env["RDAGENT_WORKSPACE"] = str(run_dir)
    env["CONDA_DEFAULT_ENV"] = env.get("CONDA_DEFAULT_ENV") or "base"
    env["BACKEND"] = env.get("BACKEND") or "rdagent.oai.backend.LiteLLMAPIBackend"
    env["FACTOR_CoSTEER_python_bin"] = env.get("FACTOR_CoSTEER_python_bin") or sys.executable
    env["FACTOR_CoSTEER_data_folder"] = env.get("FACTOR_CoSTEER_data_folder") or _FACTOR_DATA_DIR
    env["FACTOR_CoSTEER_data_folder_debug"] = (
        env.get("FACTOR_CoSTEER_data_folder_debug") or _FACTOR_DATA_DEBUG_DIR
    )

    if not env.get("OPENAI_API_KEY") and env.get("OPENCODE_AI_API_KEY"):
        env["OPENAI_API_KEY"] = env["OPENCODE_AI_API_KEY"]
        env["OPENAI_API_BASE"] = env.get("OPENCODE_AI_API_BASE") or _OPENCODE_ZEN_API_BASE
        env["OPENAI_BASE_URL"] = env["OPENAI_API_BASE"]

    openai_api_key = env.get("OPENAI_API_KEY")
    openai_api_base = env.get("OPENAI_API_BASE") or env.get("OPENAI_BASE_URL")
    if openai_api_key:
        env["LITELLM_OPENAI_API_KEY"] = env.get("LITELLM_OPENAI_API_KEY") or openai_api_key
        env["LITELLM_CHAT_OPENAI_API_KEY"] = env.get("LITELLM_CHAT_OPENAI_API_KEY") or openai_api_key
        env["LITELLM_EMBEDDING_OPENAI_API_KEY"] = env.get("LITELLM_EMBEDDING_OPENAI_API_KEY") or openai_api_key
    if openai_api_base:
        env["OPENAI_API_BASE"] = openai_api_base
        env["OPENAI_BASE_URL"] = openai_api_base
        env["LITELLM_CHAT_OPENAI_BASE_URL"] = env.get("LITELLM_CHAT_OPENAI_BASE_URL") or openai_api_base
        env["LITELLM_EMBEDDING_OPENAI_BASE_URL"] = (
            env.get("LITELLM_EMBEDDING_OPENAI_BASE_URL") or openai_api_base
        )

    if not env.get("OPENAI_API_KEY") and env.get("OLLAMA_API_BASE"):
        env["EMBEDDING_MODEL"] = env.get("EMBEDDING_MODEL") or env.get(
            "RDAGENT_OLLAMA_EMBEDDING_MODEL", _OLLAMA_EMBEDDING_MODEL
        )
        env["LITELLM_CHAT_STREAM"] = env.get("LITELLM_CHAT_STREAM") or "false"
        env["LITELLM_ENABLE_RESPONSE_SCHEMA"] = env.get("LITELLM_ENABLE_RESPONSE_SCHEMA") or "false"

    env["CHAT_MODEL"] = _resolve_chat_model(env, llm_model)
    return env


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})


@app.route("/runs/<run_id>/cancel", methods=["POST"])
def cancel_run(run_id: str):
    process = _get_running_process(run_id)
    if process is None or process.poll() is not None:
        return jsonify({"run_id": run_id, "status": "not_running"})

    logger.info("Cancelling mining run %s", run_id)
    _terminate_process(process)
    return jsonify({"run_id": run_id, "status": "cancelled"})


@app.route("/mine", methods=["POST"])
def mine():
    """Execute an RD-Agent factor mining run.

    Expected JSON body:
    {
        "run_id": "uuid",
        "config": { "scenario": "fin_factor", "max_iterations": 10, ... },
        "prompt_context": "Available data fields..."
    }
    """
    data = request.get_json(force=True)
    run_id = data.get("run_id", "unknown")
    config = data.get("config", {})
    prompt_context = data.get("prompt_context", "")

    scenario = config.get("scenario", "fin_factor")
    max_iterations = config.get("max_iterations", 10)
    llm_model = config.get("llm_model", "gpt-4o-mini")

    logger.info("Starting mining run %s scenario=%s iters=%d", run_id, scenario, max_iterations)

    run_dir = WORKSPACE / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    # Write prompt context as an additional data description file
    (run_dir / "data_description.txt").write_text(prompt_context, encoding="utf-8")

    try:
        env = _build_rdagent_env(run_dir, llm_model)
        _seed_factor_prompt_data(run_dir, env)

        cmd_parts = _build_rdagent_command(scenario, max_iterations)

        process = subprocess.Popen(
            cmd_parts,
            cwd=str(run_dir),
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            start_new_session=True,
        )
        _register_running_process(run_id, process)
        stdout, stderr = process.communicate(timeout=max_iterations * _TIMEOUT_PER_ITERATION_SECONDS)

        logger.info("rdagent exited with code %d", process.returncode)
        if process.returncode != 0:
            logger.warning("rdagent stderr: %s", stderr[:2000])

        # Parse results from workspace
        iterations = _parse_iterations(run_dir, max_iterations)
        discovered = _parse_discovered_factors(run_dir)

        status = "cancelled" if process.returncode == -signal.SIGTERM else "completed" if process.returncode == 0 else "failed"

        return jsonify({
            "status": status,
            "iterations": iterations,
            "discovered_factors": discovered,
            "error": stderr[:1000] if process.returncode != 0 else None,
        })

    except subprocess.TimeoutExpired:
        logger.error("Mining run %s timed out", run_id)
        process = _get_running_process(run_id)
        if process is not None:
            _terminate_process(process)
        return jsonify({"status": "failed", "error": "Mining run timed out", "iterations": [], "discovered_factors": []})
    except Exception as e:
        logger.exception("Mining run %s failed: %s", run_id, e)
        return jsonify({"status": "failed", "error": str(e), "traceback": traceback.format_exc(), "iterations": [], "discovered_factors": []})
    finally:
        _pop_running_process(run_id)


def _parse_iterations(run_dir: Path, max_iters: int) -> list[dict]:
    """Parse RD-Agent iteration outputs from the workspace."""
    iterations = []
    for i in range(1, max_iters + 1):
        iter_dir = run_dir / f"iteration_{i}"
        if not iter_dir.exists():
            iter_dir = run_dir / f"round_{i}"
        if not iter_dir.exists():
            continue

        hypothesis_file = iter_dir / "hypothesis.txt"
        code_file = iter_dir / "factor.py"
        metrics_file = iter_dir / "metrics.json"
        feedback_file = iter_dir / "feedback.txt"

        iteration = {
            "iteration": i,
            "hypothesis": _read_text(hypothesis_file),
            "code": _read_text(code_file),
            "metrics": _read_json(metrics_file),
            "feedback": _read_text(feedback_file),
            "status": "completed",
        }
        iterations.append(iteration)

    return iterations


def _parse_discovered_factors(run_dir: Path) -> list[dict]:
    """Parse discovered factors from the final results."""
    factors = []
    results_file = run_dir / "results" / "factors.json"
    if not results_file.exists():
        results_file = run_dir / "final_factors.json"
    if results_file.exists():
        try:
            data = json.loads(results_file.read_text(encoding="utf-8"))
            if isinstance(data, list):
                factors = data
            elif isinstance(data, dict):
                factors = data.get("factors", [])
        except (json.JSONDecodeError, OSError):
            pass
    return factors


def _read_text(path: Path) -> str | None:
    if path.exists():
        try:
            return path.read_text(encoding="utf-8")[:10000]
        except OSError:
            return None
    return None


def _read_json(path: Path) -> dict | None:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return None
    return None


if __name__ == "__main__":
    port = int(os.getenv("RDAGENT_SERVICE_PORT", os.getenv("PORT", "8001")))
    app.run(host="0.0.0.0", port=port)
