"""RD-Agent Sidecar — thin Flask wrapper around rdagent CLI.

Accepts mining requests from QuantMate's RQ worker and executes the
RD-Agent R&D loop. Returns iteration results and discovered factors.
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import sys
import traceback
from pathlib import Path

import pandas as pd
from flask import Flask, jsonify, request

app = Flask(__name__)
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("rdagent-sidecar")

WORKSPACE = Path(os.getenv("RDAGENT_WORKSPACE", "/tmp/rdagent_workspace"))
WORKSPACE.mkdir(parents=True, exist_ok=True)

_FACTOR_DATA_DIR = "git_ignore_folder/factor_implementation_source_data"
_FACTOR_DATA_DEBUG_DIR = "git_ignore_folder/factor_implementation_source_data_debug"
_OLLAMA_CHAT_MODEL = "ollama/mistral:7b"
_OLLAMA_EMBEDDING_MODEL = "ollama/nomic-embed-text:latest"
_TIMEOUT_PER_ITERATION_SECONDS = int(os.getenv("RDAGENT_TIMEOUT_PER_ITERATION_SECONDS", "900"))
_SEEDED_FACTOR_COLUMNS = {
    "$open": [10.0, 11.2, 10.8, 11.5],
    "$high": [10.4, 11.5, 11.1, 11.8],
    "$low": [9.8, 10.9, 10.6, 11.1],
    "$close": [10.2, 11.3, 10.9, 11.7],
    "$volume": [1_000_000, 1_050_000, 980_000, 1_120_000],
    "$vwap": [10.1, 11.25, 10.85, 11.6],
}
_SEEDED_FACTOR_README = """# Seeded Factor Data

These lightweight HDF5 samples are generated by the QuantMate RD-Agent sidecar.
They provide a stable prompt-time schema for factor code generation without
triggering RD-Agent's heavyweight Qlib data bootstrap.
"""


def _build_rdagent_command(scenario: str, max_iterations: int) -> list[str]:
    command = {
        "fin_factor": "fin_factor",
        "fin_model": "fin_model",
        "fin_quant": "fin_quant",
    }.get(scenario, "fin_factor")
    return ["rdagent", command, "--step-n", str(max_iterations)]


def _resolve_relative_run_path(run_dir: Path, configured_path: str) -> Path:
    path = Path(configured_path)
    return path if path.is_absolute() else run_dir / path


def _build_seed_factor_frame(debug: bool) -> pd.DataFrame:
    dates = pd.to_datetime(["2024-01-02", "2024-01-03"])
    instruments = ["SH600000"] if debug else ["SH600000", "SZ000001"]
    index = pd.MultiIndex.from_product(
        [dates, instruments],
        names=["datetime", "instrument"],
    )

    row_count = len(index)
    data = {
        column: values[:row_count]
        for column, values in _SEEDED_FACTOR_COLUMNS.items()
    }
    return pd.DataFrame(data, index=index)


def _seed_factor_prompt_data(run_dir: Path, env: dict[str, str]) -> None:
    targets = (
        (_resolve_relative_run_path(run_dir, env["FACTOR_CoSTEER_data_folder"]), _build_seed_factor_frame(False)),
        (
            _resolve_relative_run_path(run_dir, env["FACTOR_CoSTEER_data_folder_debug"]),
            _build_seed_factor_frame(True),
        ),
    )

    for target_dir, frame in targets:
        target_dir.mkdir(parents=True, exist_ok=True)

        data_path = target_dir / "daily_pv.h5"
        if not data_path.exists():
            frame.to_hdf(data_path, key="data", mode="w")

        readme_path = target_dir / "README.md"
        if not readme_path.exists():
            readme_path.write_text(_SEEDED_FACTOR_README, encoding="utf-8")


def _resolve_chat_model(env: dict[str, str], requested_model: str) -> str:
    model = requested_model.strip() if requested_model else ""
    if model.startswith("ollama/"):
        return model

    if env.get("OPENAI_API_KEY"):
        return model or env.get("CHAT_MODEL", "gpt-4o-mini")

    if env.get("OLLAMA_API_BASE"):
        return env.get("RDAGENT_OLLAMA_CHAT_MODEL", _OLLAMA_CHAT_MODEL)

    return model or env.get("CHAT_MODEL", "gpt-4o-mini")


def _build_rdagent_env(run_dir: Path, llm_model: str) -> dict[str, str]:
    env = os.environ.copy()
    env["RDAGENT_WORKSPACE"] = str(run_dir)
    env["CONDA_DEFAULT_ENV"] = env.get("CONDA_DEFAULT_ENV") or "base"
    env["FACTOR_CoSTEER_python_bin"] = env.get("FACTOR_CoSTEER_python_bin") or sys.executable
    env["FACTOR_CoSTEER_data_folder"] = env.get("FACTOR_CoSTEER_data_folder") or _FACTOR_DATA_DIR
    env["FACTOR_CoSTEER_data_folder_debug"] = (
        env.get("FACTOR_CoSTEER_data_folder_debug") or _FACTOR_DATA_DEBUG_DIR
    )

    if not env.get("OPENAI_API_KEY") and env.get("OLLAMA_API_BASE"):
        env["EMBEDDING_MODEL"] = env.get("EMBEDDING_MODEL") or env.get(
            "RDAGENT_OLLAMA_EMBEDDING_MODEL", _OLLAMA_EMBEDDING_MODEL
        )
        env["LITELLM_CHAT_STREAM"] = env.get("LITELLM_CHAT_STREAM") or "false"

    env["CHAT_MODEL"] = _resolve_chat_model(env, llm_model)
    return env


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})


@app.route("/mine", methods=["POST"])
def mine():
    """Execute an RD-Agent factor mining run.

    Expected JSON body:
    {
        "run_id": "uuid",
        "config": { "scenario": "fin_factor", "max_iterations": 10, ... },
        "prompt_context": "Available data fields..."
    }
    """
    data = request.get_json(force=True)
    run_id = data.get("run_id", "unknown")
    config = data.get("config", {})
    prompt_context = data.get("prompt_context", "")

    scenario = config.get("scenario", "fin_factor")
    max_iterations = config.get("max_iterations", 10)
    llm_model = config.get("llm_model", "gpt-4o-mini")

    logger.info("Starting mining run %s scenario=%s iters=%d", run_id, scenario, max_iterations)

    run_dir = WORKSPACE / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    # Write prompt context as an additional data description file
    (run_dir / "data_description.txt").write_text(prompt_context, encoding="utf-8")

    try:
        env = _build_rdagent_env(run_dir, llm_model)
        _seed_factor_prompt_data(run_dir, env)

        cmd_parts = _build_rdagent_command(scenario, max_iterations)

        result = subprocess.run(
            cmd_parts,
            cwd=str(run_dir),
            env=env,
            capture_output=True,
            text=True,
            timeout=max_iterations * _TIMEOUT_PER_ITERATION_SECONDS,
        )

        logger.info("rdagent exited with code %d", result.returncode)
        if result.returncode != 0:
            logger.warning("rdagent stderr: %s", result.stderr[:2000])

        # Parse results from workspace
        iterations = _parse_iterations(run_dir, max_iterations)
        discovered = _parse_discovered_factors(run_dir)

        return jsonify({
            "status": "completed" if result.returncode == 0 else "failed",
            "iterations": iterations,
            "discovered_factors": discovered,
            "error": result.stderr[:1000] if result.returncode != 0 else None,
        })

    except subprocess.TimeoutExpired:
        logger.error("Mining run %s timed out", run_id)
        return jsonify({"status": "failed", "error": "Mining run timed out", "iterations": [], "discovered_factors": []})
    except Exception as e:
        logger.exception("Mining run %s failed: %s", run_id, e)
        return jsonify({"status": "failed", "error": str(e), "traceback": traceback.format_exc(), "iterations": [], "discovered_factors": []})


def _parse_iterations(run_dir: Path, max_iters: int) -> list[dict]:
    """Parse RD-Agent iteration outputs from the workspace."""
    iterations = []
    for i in range(1, max_iters + 1):
        iter_dir = run_dir / f"iteration_{i}"
        if not iter_dir.exists():
            iter_dir = run_dir / f"round_{i}"
        if not iter_dir.exists():
            continue

        hypothesis_file = iter_dir / "hypothesis.txt"
        code_file = iter_dir / "factor.py"
        metrics_file = iter_dir / "metrics.json"
        feedback_file = iter_dir / "feedback.txt"

        iteration = {
            "iteration": i,
            "hypothesis": _read_text(hypothesis_file),
            "code": _read_text(code_file),
            "metrics": _read_json(metrics_file),
            "feedback": _read_text(feedback_file),
            "status": "completed",
        }
        iterations.append(iteration)

    return iterations


def _parse_discovered_factors(run_dir: Path) -> list[dict]:
    """Parse discovered factors from the final results."""
    factors = []
    results_file = run_dir / "results" / "factors.json"
    if not results_file.exists():
        results_file = run_dir / "final_factors.json"
    if results_file.exists():
        try:
            data = json.loads(results_file.read_text(encoding="utf-8"))
            if isinstance(data, list):
                factors = data
            elif isinstance(data, dict):
                factors = data.get("factors", [])
        except (json.JSONDecodeError, OSError):
            pass
    return factors


def _read_text(path: Path) -> str | None:
    if path.exists():
        try:
            return path.read_text(encoding="utf-8")[:10000]
        except OSError:
            return None
    return None


def _read_json(path: Path) -> dict | None:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return None
    return None


if __name__ == "__main__":
    port = int(os.getenv("RDAGENT_SERVICE_PORT", os.getenv("PORT", "8001")))
    app.run(host="0.0.0.0", port=port)
